// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/trade (or src/types/trade.ts) instead.
/**
 * cabinetPlacedItem — the SHARED conversion between trade `ConfiguredCabinet`
 * records and engine `PlacedItem`s (implementation plan §11.1: one module so
 * the two directions cannot drift). Pure functions, no React/Supabase deps.
 *
 * `toPlacedItems` was extracted verbatim from useTradeRoomPricing.ts, which
 * now re-exports it. `proposalToTradeRoom.ts` is the forward direction.
 */

import type { PlacedItem } from '../layout/core.ts';
import type { ConfiguredCabinet, RoomMaterialDefaults } from './tradeTypes.ts';

export function toPlacedItems(cabinets: ConfiguredCabinet[], materialDefaults?: RoomMaterialDefaults): PlacedItem[] {
  return cabinets.map((cabinet) => ({
    instanceId: cabinet.instanceId,
    definitionId: cabinet.definitionId,
    itemType: cabinet.category === 'Appliance' ? 'Appliance' : 'Cabinet',
    cabinetNumber: cabinet.cabinetNumber,
    x: cabinet.position?.x ?? 0,
    y: cabinet.position?.y ?? 0,
    z: cabinet.position?.z ?? 0,
    rotation: cabinet.position?.rotation ?? 0,
    width: cabinet.dimensions.width,
    depth: cabinet.dimensions.depth,
    height: cabinet.dimensions.height,
    hinge: 'Left',
    finishColor: cabinet.materials?.exteriorFinish ?? materialDefaults?.exteriorFinish,
    carcaseMaterialId: cabinet.materials?.carcaseFinish ?? materialDefaults?.carcaseFinish,
    exteriorMaterialId: cabinet.materials?.exteriorFinish ?? materialDefaults?.exteriorFinish,
    edgeId: cabinet.materials?.edgeBanding ?? materialDefaults?.edgeBanding,
    handleType: cabinet.hardware?.handleType,
    endPanelLeft: cabinet.construction?.endPanelLeft,
    endPanelRight: cabinet.construction?.endPanelRight,
    fillerLeft: cabinet.construction?.leftFillerWidth,
    fillerRight: cabinet.construction?.rightFillerWidth,
    blindSide: cabinet.construction?.blindSide,
    drawerFrontHeights: cabinet.construction?.drawerFrontHeights,
  }));
}

/** Deterministic Base/Wall/Tall/Appliance classification for engine output. */
export function categoryForDefinition(definitionId: string): ConfiguredCabinet['category'] {
  if (definitionId.includes('opening')) return 'Appliance';
  if (definitionId.startsWith('wall_') || definitionId === 'fridge_top_cabinet') return 'Wall';
  if (definitionId.startsWith('tall_')) return 'Tall';
  return 'Base';
}
