/**
 * GENERATED — do not edit by hand.
 *
 * Exact construction recipes read from the real Microvellum product workbooks
 * (microvellum_product_prompts), for every product the planner can place.
 *
 * Replaces fuzzy name matching for these 42 products. The values here are
 * Microvellum's own, and several differ materially from the hand-written
 * constants they supersede:
 *
 *   backPanelThickness  16 -> 6      backPanelSetback  16 -> 0
 *   topReveal (base)     1 -> 2      bottomReveal       1 -> 0
 *   toeKick.setback     50 -> 0      toeKick thickness 16 -> 15
 *   benchtop thickness  20 -> 40     benchtop overhang 20 -> 45
 *
 * Regenerate with scratchpad/gen-recipes.mjs + emit-recipes.mjs.
 *
 * NOTE: hasTopPanel follows the category convention (base = rails, no top),
 * NOT Microvellum's Use_Tops, which reports true for base cabinets. Changing
 * that would disagree with the parts engine, which bills 'Rail On Flat' x2 on
 * a base. 13 products differ on this point — see mvUseTops in the source data.
 */
import type { ConstructionRecipe } from './constructionRecipes';

export const MV_GENERATED_RECIPES: Record<string, ConstructionRecipe> = {
  "Base 1 Door": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 1 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base 1 Door 1 Drawer": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'COMBO', combo: { topDrawers: 1, bottomDoors: 1, dividerThickness: 18 } },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base 1 Door Sink": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'SINK' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base 2 Door": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 2 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base 2 Door 1 Drawer": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'COMBO', combo: { topDrawers: 1, bottomDoors: 2, dividerThickness: 18 } },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base 2 Door Sink": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'SINK' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base 3 Drawer": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DRAWERS', drawers: { drawerCount: 3, gap: 2, showBox: true } },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base 4 Drawer": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DRAWERS', drawers: { drawerCount: 4, gap: 2, showBox: true } },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base Applied Panel": {
    category: 'Accessory',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Base Blind Corner": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 2 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 25 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'CORNER' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base Corner Diagonal Cabinet": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'CORNER' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 0, sideOverhang: 0 },
  },
  "Base Open": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6.35, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 27, sideOverhang: 0 },
  },
  "Base Pullout": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Base Return Filler": {
    category: 'Accessory',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Base Scribe Filler": {
    category: 'Accessory',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Base Under Counter Oven": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'APPLIANCE_OPENING' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Corner Filler With Cleats": {
    category: 'Accessory',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Integrated Dishwasher": {
    category: 'Base',
    carcass: { hasBottomPanel: true, hasTopPanel: false, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 2, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'APPLIANCE_OPENING' },
    benchtop: { enabled: true, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Tall 1 Door": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 1 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Tall 2 Door": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 2 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Tall 2 Door Broom Cabinet": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 2 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Tall 2 Door Pantry": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 2 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Tall Applied Panel": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Tall Fridge Cabinet": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 2 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'APPLIANCE_OPENING' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 0, sideOverhang: 0 },
  },
  "Tall Open": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6.35, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 27, sideOverhang: 0 },
  },
  "Tall Return Filler": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Tall Wall Oven With Microwave": {
    category: 'Tall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 4, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'APPLIANCE_OPENING' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Toe Kick Base": {
    category: 'Accessory',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 1, bottomReveal: 1, sideReveal: 1 },
    shelves: { count: 1, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: true, height: 135, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Upper 1 Door": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 1 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Upper 1 Door Glass Door": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6.35, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 1 as 1 | 2, glassDoor: true, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 27, sideOverhang: 0 },
  },
  "Upper 2 Door": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 2 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Upper 2 Door Glass Door": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6.35, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 2 as 1 | 2, glassDoor: true, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 27, sideOverhang: 0 },
  },
  "Upper 3 Door": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'DOORS', doors: { doorCount: 2 as 1 | 2, glassDoor: false, overlay: 'full', gap: 2 } },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Upper Applied Panel": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Upper Blind Corner": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 2 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'CORNER' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Upper Corner Diagonal Cabinet": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'CORNER' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 0, sideOverhang: 0 },
  },
  "Upper Corner Open Cabinet": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6.35, backPanelSetback: 0, topReveal: 1, bottomReveal: 1, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'CORNER' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Upper Microwave Cabinet": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'APPLIANCE_OPENING' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Upper Open": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6.35, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 27, sideOverhang: 0 },
  },
  "Upper Rangehood Cabinet": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6, backPanelSetback: 0, topReveal: 0, bottomReveal: 40, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'APPLIANCE_OPENING' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 45, sideOverhang: 0 },
  },
  "Upper Return Filler": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 16, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 16, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 0, frontOverhang: 0, sideOverhang: 0 },
  },
  "Upper Winerack": {
    category: 'Wall',
    carcass: { hasBottomPanel: true, hasTopPanel: true, gableThickness: 16, backPanelThickness: 6.35, backPanelSetback: 0, topReveal: 0, bottomReveal: 0, sideReveal: 1 },
    shelves: { count: 2, adjustable: true, setback: 5, thickness: 16 },
    toeKick: { enabled: false, height: 0, setback: 0, kickboardThickness: 15, legCount: 4 },
    fronts: { type: 'OPEN' },
    benchtop: { enabled: false, thickness: 40, frontOverhang: 27, sideOverhang: 0 },
  },
};

/** Microvellum LinkID for each generated recipe, for traceability. */
export const MV_GENERATED_LINK_IDS: Record<string, string> = {
  "Base 1 Door": "211EKCBKCC1F",
  "Base 1 Door 1 Drawer": "211INMJ75TLF",
  "Base 1 Door Sink": "211FO8A9EFDF",
  "Base 2 Door": "211EKDJ3PL6F",
  "Base 2 Door 1 Drawer": "211INN9DUBFF",
  "Base 2 Door Sink": "211FO93E07PF",
  "Base 3 Drawer": "2128QBTOJX8F",
  "Base 4 Drawer": "2128QAV3CHGF",
  "Base Applied Panel": "211ML6441S6F",
  "Base Blind Corner": "211EP1ZFBTBF",
  "Base Corner Diagonal Cabinet": "211INGPEM6DF",
  "Base Open": "211ENO4C83OF",
  "Base Pullout": "234KMF8WQ8LF",
  "Base Return Filler": "211LW4HX7EYF",
  "Base Scribe Filler": "211ML7ZV04FF",
  "Base Under Counter Oven": "2128T68XX0CF",
  "Corner Filler With Cleats": "2115QOFZGWDF",
  "Integrated Dishwasher": "259AK93OS9VF",
  "Tall 1 Door": "211EO3N5KD6F",
  "Tall 2 Door": "211EO55ARZRF",
  "Tall 2 Door Broom Cabinet": "211QS0HYFAVF",
  "Tall 2 Door Pantry": "211IQ4DJI3PF",
  "Tall Applied Panel": "211ML8W6S8FF",
  "Tall Fridge Cabinet": "211KNARLZ4FF",
  "Tall Open": "213NP6XNS4KF",
  "Tall Return Filler": "211LW59DI5GF",
  "Tall Wall Oven With Microwave": "2197K0DZQCNF",
  "Toe Kick Base": "211RV8GM6SEF",
  "Upper 1 Door": "211EOANTJ2XF",
  "Upper 1 Door Glass Door": "2129I8KRJRBF",
  "Upper 2 Door": "211EOB5Y497F",
  "Upper 2 Door Glass Door": "2129I7RVF5DF",
  "Upper 3 Door": "211ILGGUZ9AF",
  "Upper Applied Panel": "211MLAQGNK6F",
  "Upper Blind Corner": "211EP5J1CYZF",
  "Upper Corner Diagonal Cabinet": "211INH1T1VUF",
  "Upper Corner Open Cabinet": "211IMG3A3AXF",
  "Upper Microwave Cabinet": "218NNG92X7DF",
  "Upper Open": "211EOCU1WLEF",
  "Upper Rangehood Cabinet": "211MO4HYLZJF",
  "Upper Return Filler": "211LW75COPMF",
  "Upper Winerack": "211ILMQOW35F",
};
