// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/roomDocument instead.
import type { RoomDocumentV1, RoomObject, RoomPlacement, RoomPoint } from './types.ts';

const EPS = 1e-7;
const diff = (a: RoomPoint, b: RoomPoint): RoomPoint => ({ xMm: a.xMm - b.xMm, zMm: a.zMm - b.zMm });
const dot = (a: RoomPoint, b: RoomPoint): number => a.xMm * b.xMm + a.zMm * b.zMm;
const cross = (a: RoomPoint, b: RoomPoint): number => a.xMm * b.zMm - a.zMm * b.xMm;
const norm = (v: RoomPoint): number => Math.hypot(v.xMm, v.zMm);

export interface WallGeometry {
  start: RoomPoint;
  end: RoomPoint;
  lengthMm: number;
  angleDeg: number;
  tangent: RoomPoint;
  inwardNormal: RoomPoint;
  /** Rotation used by the existing planner cabinets; degrees about the Y axis. */
  rotationDeg: number;
}

export function wallGeometry(doc: RoomDocumentV1, wallId: string): WallGeometry | null {
  const wall = doc.walls.find(item => item.id === wallId);
  if (!wall) return null;
  const a = doc.corners.find(item => item.id === wall.startCornerId);
  const b = doc.corners.find(item => item.id === wall.endCornerId);
  if (!a || !b) return null;
  const start = { xMm: a.xMm, zMm: a.zMm };
  const end = { xMm: b.xMm, zMm: b.zMm };
  const direction = diff(end, start);
  const lengthMm = norm(direction);
  if (lengthMm <= EPS) return null;
  const tangent = { xMm: direction.xMm / lengthMm, zMm: direction.zMm / lengthMm };
  const side = wall.interiorSide === 'right' ? -1 : 1;
  const inwardNormal = { xMm: -tangent.zMm * side, zMm: tangent.xMm * side };
  const rotationDeg = Math.atan2(-inwardNormal.xMm, inwardNormal.zMm) * 180 / Math.PI;
  return { start, end, lengthMm, angleDeg: Math.atan2(tangent.zMm, tangent.xMm) * 180 / Math.PI, tangent, inwardNormal, rotationDeg };
}

export function projectToWall(doc: RoomDocumentV1, wallId: string, point: RoomPoint): {
  projected: RoomPoint; offsetMm: number; rawOffsetMm: number; distanceMm: number;
} | null {
  const wall = wallGeometry(doc, wallId);
  if (!wall) return null;
  const rawOffsetMm = dot(diff(point, wall.start), wall.tangent);
  const offsetMm = Math.max(0, Math.min(wall.lengthMm, rawOffsetMm));
  const projected = {
    xMm: wall.start.xMm + wall.tangent.xMm * offsetMm,
    zMm: wall.start.zMm + wall.tangent.zMm * offsetMm,
  };
  return { projected, offsetMm, rawOffsetMm, distanceMm: norm(diff(point, projected)) };
}

export interface ObjectPose { xMm: number; zMm: number; rotationDeg: number }
export function placementPose(doc: RoomDocumentV1, placement: RoomPlacement, widthMm: number, depthMm: number): ObjectPose | null {
  if (placement.type === 'free') return { xMm: placement.xMm, zMm: placement.zMm, rotationDeg: placement.rotationDeg };
  const wall = wallGeometry(doc, placement.wallId);
  if (!wall) return null;
  const along = placement.offsetMm + widthMm / 2;
  const inward = (placement.depthOffsetMm ?? 0) + depthMm / 2;
  return {
    xMm: wall.start.xMm + wall.tangent.xMm * along + wall.inwardNormal.xMm * inward,
    zMm: wall.start.zMm + wall.tangent.zMm * along + wall.inwardNormal.zMm * inward,
    rotationDeg: wall.rotationDeg,
  };
}

export function objectPose(doc: RoomDocumentV1, object: RoomObject): ObjectPose | null {
  return placementPose(doc, object.placement, object.widthMm, object.depthMm);
}

export function footprintCorners(pose: ObjectPose, widthMm: number, depthMm: number): RoomPoint[] {
  const angle = pose.rotationDeg * Math.PI / 180;
  const c = Math.cos(angle), s = Math.sin(angle);
  // CabinetMesh applies a negative Y rotation. In plan that turns its local
  // width axis toward +z for positive planner degrees.
  return [
    [-widthMm / 2, -depthMm / 2], [widthMm / 2, -depthMm / 2],
    [widthMm / 2, depthMm / 2], [-widthMm / 2, depthMm / 2],
  ].map(([x, z]) => ({ xMm: pose.xMm + c * x - s * z, zMm: pose.zMm + s * x + c * z }));
}

function onSegment(p: RoomPoint, a: RoomPoint, b: RoomPoint, toleranceMm = EPS): boolean {
  const ab = diff(b, a), ap = diff(p, a);
  const length = norm(ab);
  return length > EPS && Math.abs(cross(ab, ap)) / length <= toleranceMm
    && dot(ap, ab) >= -toleranceMm * length
    && dot(diff(p, b), ab) <= toleranceMm * length;
}

/** Boundary points count as contained; an unconfirmed floor is never inferred. */
export function pointInPolygon(point: RoomPoint, polygon: RoomPoint[]): boolean {
  if (polygon.length < 3) return false;
  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const a = polygon[j], b = polygon[i];
    if (onSegment(point, a, b)) return true;
    if ((a.zMm > point.zMm) !== (b.zMm > point.zMm)
      && point.xMm < a.xMm + (b.xMm - a.xMm) * (point.zMm - a.zMm) / (b.zMm - a.zMm)) inside = !inside;
  }
  return inside;
}

/** Returns proper or endpoint intersection. Parallel overlapping edges are
 * handled by the containment sampler's endpoint checks. */
export function segmentIntersection(a: RoomPoint, b: RoomPoint, c: RoomPoint, d: RoomPoint): {
  point: RoomPoint; t: number; u: number;
} | null {
  const r = diff(b, a), s = diff(d, c), divisor = cross(r, s);
  if (Math.abs(divisor) < EPS) return null;
  const delta = diff(c, a);
  const t = cross(delta, s) / divisor, u = cross(delta, r) / divisor;
  if (t < -EPS || t > 1 + EPS || u < -EPS || u > 1 + EPS) return null;
  return { point: { xMm: a.xMm + r.xMm * t, zMm: a.zMm + r.zMm * t }, t, u };
}

export function confirmedFloorPolygon(doc: RoomDocumentV1): RoomPoint[] | null {
  if (!doc.floorBoundary?.confirmed) return null;
  const corners = new Map(doc.corners.map(corner => [corner.id, corner]));
  const vertices = doc.floorBoundary.cornerIds.map(id => corners.get(id));
  if (vertices.length < 3 || vertices.some(vertex => !vertex)) return null;
  return vertices.map(vertex => ({ xMm: vertex!.xMm, zMm: vertex!.zMm }));
}

/** An edge of an oriented footprint may pass through a concave void even if
 * all its corners are inside. Split each edge at boundary crossings and test
 * every interval midpoint, including crossings at reflex vertices. */
export function footprintInsidePolygon(footprint: RoomPoint[], polygon: RoomPoint[]): boolean {
  if (footprint.length < 3 || polygon.length < 3) return false;
  if (!footprint.every(point => pointInPolygon(point, polygon))) return false;
  for (let i = 0; i < footprint.length; i++) {
    const a = footprint[i], b = footprint[(i + 1) % footprint.length];
    const cuts = [0, 1];
    for (let j = 0; j < polygon.length; j++) {
      const hit = segmentIntersection(a, b, polygon[j], polygon[(j + 1) % polygon.length]);
      if (hit) cuts.push(Math.max(0, Math.min(1, hit.t)));
    }
    cuts.sort((x, y) => x - y);
    for (let k = 1; k < cuts.length; k++) {
      if (cuts[k] - cuts[k - 1] < EPS) continue;
      const t = (cuts[k] + cuts[k - 1]) / 2;
      if (!pointInPolygon({ xMm: a.xMm + (b.xMm - a.xMm) * t, zMm: a.zMm + (b.zMm - a.zMm) * t }, polygon)) return false;
    }
  }
  return true;
}

export function footprintInsideConfirmedFloor(doc: RoomDocumentV1, footprint: RoomPoint[]): {
  status: 'inside' | 'outside' | 'unconfirmed'; reason?: string;
} {
  const polygon = confirmedFloorPolygon(doc);
  if (!polygon) return { status: 'unconfirmed', reason: 'A confirmed floor boundary is required for room-wide clearance.' };
  return footprintInsidePolygon(footprint, polygon)
    ? { status: 'inside' }
    : { status: 'outside', reason: 'The object crosses the actual floor boundary.' };
}

/** Separating-axis test for convex footprints. Touching edges may abut. */
export function footprintsIntersect(a: RoomPoint[], b: RoomPoint[], toleranceMm = 0): boolean {
  if (a.length < 3 || b.length < 3) return false;
  for (const polygon of [a, b]) {
    for (let i = 0; i < polygon.length; i++) {
      const edge = diff(polygon[(i + 1) % polygon.length], polygon[i]);
      const axis = { xMm: -edge.zMm, zMm: edge.xMm };
      const len = norm(axis);
      if (len < EPS) continue;
      const projection = (points: RoomPoint[]) => points.map(point => dot(point, axis) / len);
      const ap = projection(a), bp = projection(b);
      if (Math.max(...ap) <= Math.min(...bp) + toleranceMm
        || Math.max(...bp) <= Math.min(...ap) + toleranceMm) return false;
    }
  }
  return true;
}

export function derivedLegacyBounds(doc: RoomDocumentV1): {
  minX: number; minZ: number; maxX: number; maxZ: number; widthMm: number; depthMm: number;
} | null {
  if (!doc.corners.length) return null;
  const xs = doc.corners.map(c => c.xMm), zs = doc.corners.map(c => c.zMm);
  const minX = Math.min(...xs), maxX = Math.max(...xs), minZ = Math.min(...zs), maxZ = Math.max(...zs);
  return { minX, minZ, maxX, maxZ, widthMm: maxX - minX, depthMm: maxZ - minZ };
}
