// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/roomDocument instead.
export * from './core.ts';
export { migrateTradeRoom } from './migrate.ts';
export { reconcileTradeRoomCabinets, cabinetFootprintDepthMm } from './reconcile.ts';
export { RoomRevisionConflictError, mergeRoomWrite, mergeCabinetWrite, selectRoomsForWrite, saveRoomSetupEdit } from './persistence.ts';
export type { CabinetWrite } from './persistence.ts';
