// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/roomDocument instead.
export type {
  RoomPoint, DimensionSource, DimensionValue, RoomCorner, RoomWall, RoomWallChain,
  ConfirmedFloorBoundary, RoomOpening, RoomPlacement, RoomService, RoomObject,
  RoomDocumentV1, RoomEdit, RoomIssue, RoomEditResult,
} from './types.ts';
export {
  wallGeometry, projectToWall, placementPose, objectPose, footprintCorners,
  pointInPolygon, segmentIntersection, confirmedFloorPolygon,
  footprintInsidePolygon, footprintInsideConfirmedFloor, footprintsIntersect,
  derivedLegacyBounds,
} from './geometry.ts';
export { validateRoomDocument, polygonSelfIntersects } from './validate.ts';
export { createRoomDocument, applyRoomEdit, undoRoomEdit } from './edit.ts';
export { migrateTradeRoom } from './migrate.ts';
export { reconcileTradeRoomCabinets, cabinetFootprintDepthMm } from './reconcile.ts';
export { RoomRevisionConflictError, mergeRoomWrite, mergeCabinetWrite, selectRoomsForWrite } from './persistence.ts';
export type { CabinetWrite } from './persistence.ts';
