// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/roomDocument instead.
import type { TradeRoom } from '../trade/tradeTypes.ts';
import { polygonFromRoom } from '../layout/polygon.ts';
import { createRoomDocument } from './edit.ts';
import { cabinetFootprintDepthMm } from './reconcile.ts';
import type { RoomDocumentV1, RoomObject, RoomOpening, RoomService } from './types.ts';

/** Convert a saved rectangle/L room once, without modifying its original
 * record. The explicit legacy outline establishes topology, but no old length
 * is relabelled as a tape measurement. Cabinet sizes stay fixed by default. */
export function migrateTradeRoom(room: TradeRoom): RoomDocumentV1 {
  if (room.roomDocument) {
    if (room.roomDocument.version !== 1) throw new Error('Unsupported room document version');
    return structuredClone(room.roomDocument);
  }
  const doc = createRoomDocument(room.id, room.name);
  const polygon = polygonFromRoom(room.config);
  const cornerIds = polygon.vertices.map((_, index) => `${room.id}:corner:${index + 1}`);
  const vertexIndex = (point: { x: number; z: number }) => polygon.vertices.findIndex(vertex =>
    Math.abs(vertex.x - point.x) < 0.001 && Math.abs(vertex.z - point.z) < 0.001);
  doc.corners = polygon.vertices.map((point, index) => ({ id: cornerIds[index], xMm: point.x, zMm: point.z }));
  doc.walls = polygon.segments.map(segment => ({
    id: segment.id,
    startCornerId: cornerIds[vertexIndex(segment.a)],
    endCornerId: cornerIds[vertexIndex(segment.b)],
    interiorSide: 'left' as const,
    height: room.config.height > 0 ? { valueMm: room.config.height, source: 'unknown' as const } : undefined,
    lengthEvidence: { valueMm: segment.length, source: 'unknown' as const, reason: 'Legacy room setup; measurement provenance unavailable.' },
  }));
  doc.chains = [{ id: `${room.id}:perimeter`, wallIds: doc.walls.map(wall => wall.id), closed: true }];
  doc.floorBoundary = { cornerIds, confirmed: true };
  const wallIds = new Set(doc.walls.map(wall => wall.id));
  doc.openings = (room.config.openings ?? []).map((opening): RoomOpening => ({
    id: opening.id,
    wallId: wallIds.has(opening.wall) ? opening.wall : doc.walls[0].id,
    kind: opening.type,
    offsetMm: opening.offsetMm,
    widthMm: opening.widthMm,
    heightMm: opening.heightMm,
    sillHeightMm: opening.sillHeightMm,
    swing: opening.swing,
    dimensionEvidence: {
      offsetMm: { valueMm: opening.offsetMm, source: 'unknown' },
      widthMm: { valueMm: opening.widthMm, source: 'unknown' },
    },
  }));
  doc.services = (room.config.services ?? []).map((service): RoomService => ({
    id: service.id,
    kind: service.type,
    placement: service.placement === 'floor' && Number.isFinite(service.xMm) && Number.isFinite(service.zMm)
      ? { type: 'free', xMm: service.xMm!, zMm: service.zMm!, rotationDeg: 0 }
      : { type: 'wall', wallId: wallIds.has(service.wall) ? service.wall : doc.walls[0].id, offsetMm: service.offsetMm },
    heightMm: service.heightMm,
  }));
  doc.objects = (room.cabinets ?? []).map((cabinet): RoomObject => ({
    id: cabinet.instanceId,
    layer: 'proposed',
    kind: cabinet.category === 'Appliance' ? 'appliance' : 'cabinet',
    placement: cabinet.wallAttachment && wallIds.has(cabinet.wallAttachment.wallId)
      ? { type: 'wall', ...cabinet.wallAttachment }
      : {
        type: 'free',
        xMm: cabinet.position?.x ?? 0,
        zMm: cabinet.position?.z ?? 0,
        rotationDeg: cabinet.position?.rotation ?? 0,
      },
    widthMm: cabinet.dimensions.width,
    depthMm: cabinetFootprintDepthMm(cabinet),
    heightMm: cabinet.dimensions.height,
    elevationMm: cabinet.category === 'Wall'
      ? (cabinet.position?.y || room.dimensions?.wallMountHeight || 1350)
      : (cabinet.position?.y ?? 0),
    catalogueId: cabinet.definitionId,
    sourceCabinetId: cabinet.instanceId,
    sizeLock: cabinet.dimensionStatus === 'inferred' ? 'none' : 'confirmed',
    dimensionEvidence: {
      widthMm: { valueMm: cabinet.dimensions.width, source: 'unknown' },
      depthMm: { valueMm: cabinetFootprintDepthMm(cabinet), source: 'unknown' },
      heightMm: { valueMm: cabinet.dimensions.height, source: 'unknown' },
    },
  }));
  // Retain a recoverable pre-migration copy without recursively storing a
  // document inside itself. The TradeRoom alongside this document is intact.
  const { roomDocument: _document, ...legacy } = room;
  doc.legacySnapshot = structuredClone(legacy);
  return doc;
}
