// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/roomDocument instead.
import type { ConfiguredCabinet, TradeRoom } from '../trade/tradeTypes.ts';
import { reconcileTradeRoomCabinets } from './reconcile.ts';

/** A local draft remains available when another device has saved this room. */
export class RoomRevisionConflictError extends Error {
  readonly code = 'room-revision-conflict';
  constructor(readonly roomId: string, readonly expectedRevision: number | null,
    readonly actualRevision: number | null) {
    super(`Room ${roomId} changed on another device (expected revision ${expectedRevision ?? 'legacy'}, found ${actualRevision ?? 'legacy'}).`);
    this.name = 'RoomRevisionConflictError';
  }
}

/** A single room write is merged into the freshly loaded job. An explicit null
 * means the client loaded a legacy room without a RoomDocument; undefined
 * means no revision guard was requested (e.g. creating a room). */
export function mergeRoomWrite(latestRooms: TradeRoom[], requestedRoom: TradeRoom,
  expectedRevision?: number | null): TradeRoom[] {
  const latest = latestRooms.find(room => room.id === requestedRoom.id);
  const actualRevision = latest?.roomDocument?.revision ?? null;
  if (expectedRevision !== undefined && (!latest || actualRevision !== expectedRevision)) {
    throw new RoomRevisionConflictError(requestedRoom.id, expectedRevision, actualRevision);
  }
  return latest
    ? latestRooms.map(room => room.id === requestedRoom.id ? requestedRoom : room)
    : [...latestRooms, requestedRoom];
}

/** The setup wizard may stay open while the same room is edited elsewhere.
 * Save against the revision present when the wizard opened, then update the
 * local room only after the server accepts the write. A rejected write leaves
 * the wizard's draft intact for review. */
export async function saveRoomSetupEdit(
  jobId: string,
  originalRoom: TradeRoom,
  editedRoom: TradeRoom,
  persist: (input: { jobId: string; room: TradeRoom; expectedRoomRevision: number | null }) => Promise<unknown>,
  updateLocal: (roomId: string, room: TradeRoom) => void,
): Promise<void> {
  if (originalRoom.id !== editedRoom.id) throw new Error('The room setup edit changed room identity.');
  await persist({ jobId, room: editedRoom, expectedRoomRevision: originalRoom.roomDocument?.revision ?? null });
  updateLocal(editedRoom.id, editedRoom);
}

export type CabinetWrite =
  | { type: 'upsert'; roomId: string; cabinet: ConfiguredCabinet; roomFallback?: TradeRoom }
  | { type: 'remove'; roomId: string; instanceId: string };

/** Apply one cabinet mutation to the freshly read room. A cached fallback is
 * only used when the room does not exist yet; it never replaces a saved room. */
export function mergeCabinetWrite(latestRooms: TradeRoom[], change: CabinetWrite): TradeRoom[] {
  const latestRoom = latestRooms.find(room => room.id === change.roomId);
  if (!latestRoom && change.type === 'remove') return latestRooms;
  if (!latestRoom && change.type === 'upsert' && !change.roomFallback) {
    throw new Error(`Room ${change.roomId} is missing from the cabinet save request.`);
  }

  const baseRoom = latestRoom ?? (change.type === 'upsert' ? change.roomFallback : undefined);
  if (!baseRoom) return latestRooms;
  const cabinets = change.type === 'upsert'
    ? (latestRoom
      ? baseRoom.cabinets.some(cabinet => cabinet.instanceId === change.cabinet.instanceId)
        ? baseRoom.cabinets.map(cabinet => cabinet.instanceId === change.cabinet.instanceId ? change.cabinet : cabinet)
        : [...baseRoom.cabinets, change.cabinet]
      : [change.cabinet])
    : baseRoom.cabinets.filter(cabinet => cabinet.instanceId !== change.instanceId);
  const roomDocument = baseRoom.roomDocument
    ? reconcileTradeRoomCabinets(baseRoom.roomDocument, cabinets, baseRoom.dimensions)
    : undefined;
  const updatedRoom: TradeRoom = {
    ...baseRoom,
    cabinets,
    ...(roomDocument ? { roomDocument } : {}),
    updatedAt: new Date(),
  };
  return latestRoom
    ? latestRooms.map(room => room.id === change.roomId ? updatedRoom : room)
    : [...latestRooms, updatedRoom];
}

/** Pricing and quote writes retain the fresh server rooms; only an explicit
 * room or cabinet mutation may alter them. */
export function selectRoomsForWrite(latestRooms: TradeRoom[], requestedRooms: TradeRoom[], options: {
  roomWrite?: { roomId: string; expectedRoomRevision?: number | null };
  cabinetWrite?: CabinetWrite;
  retainLatestRooms?: boolean;
  hasServerJob: boolean;
}): TradeRoom[] {
  if (options.roomWrite) {
    const requested = requestedRooms.find(room => room.id === options.roomWrite!.roomId);
    if (!requested) throw new Error(`Room ${options.roomWrite.roomId} is missing from the save request.`);
    return mergeRoomWrite(latestRooms, requested, options.roomWrite.expectedRoomRevision);
  }
  if (options.cabinetWrite) return mergeCabinetWrite(latestRooms, options.cabinetWrite);
  if (options.retainLatestRooms && options.hasServerJob) return latestRooms;
  return requestedRooms;
}
