// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/layout instead.
/**
 * candidateGenerator — deterministic candidate pool before AI ranking
 * (implementation plan §7.1 / Phase D2).
 *
 * Enumerates feasible layout strategies and emphasis variants for a brief,
 * compiles each with the real engine, rejects hard errors, scores survivors
 * (designScore.ts), removes near-duplicates and returns a diverse ranked
 * pool. No randomness: identical input always yields the identical pool, in
 * the same order. AI may rank/explain these candidates but never invents
 * geometry.
 */

import type { DesignBrief, KitchenSpec, Segment, SegmentRole, StyleSpec, Violation, Wall } from './types.ts';
import type { PlacedItem } from './core.ts';
import { rangeForWall } from './briefConstraints.ts';
import { compileSpec } from './compileSpec.ts';
import { validate } from './validate.ts';
import { priceDesign } from './priceDesign.ts';
import { defaultSpecFor, inferLayoutShapeFromWalls, type LayoutShape } from './defaultSpec.ts';
import { scoreDesign, type DesignScore } from './designScore.ts';

export type CandidateEmphasis = 'workflow' | 'storage' | 'social';

export interface DesignCandidate {
  /** deterministic id: strategy/emphasis/sink-wall */
  candidateId: string;
  strategy: LayoutShape;
  emphasis: CandidateEmphasis;
  spec: KitchenSpec;
  items: PlacedItem[];
  violations: Violation[];
  priceBand: { lowAud: number; highAud: number };
  score: DesignScore;
  /** structural signature used for de-duplication */
  fingerprint: string;
}

export interface RejectedCandidate {
  candidateId: string;
  strategy: LayoutShape;
  emphasis: CandidateEmphasis;
  reasons: string[];
}

export interface CandidatePool {
  candidates: DesignCandidate[];
  rejected: RejectedCandidate[];
  /** every strategy that was attempted for this room/brief */
  attemptedStrategies: LayoutShape[];
}

export interface GenerateCandidatesInput {
  brief: DesignBrief;
  /** strategies the customer allows; defaults to all four */
  allowedStrategies?: LayoutShape[];
  style?: StyleSpec;
  /** maximum returned candidates (default 3) */
  maxCandidates?: number;
}

const ALL_STRATEGIES: LayoutShape[] = ['single-wall', 'l-shape', 'u-shape', 'galley'];

function seg(role: SegmentRole, widthMm?: number): Segment {
  return { kind: 'cabinet', role, ...(widthMm ? { widthMm } : {}) };
}

/** Cheap geometric pre-filter; final authority is compile + validate. */
function strategyPlausible(strategy: LayoutShape, brief: DesignBrief): boolean {
  const { width, depth } = brief.room;
  const selectedShape = brief.allowedWalls?.length
    ? inferLayoutShapeFromWalls(brief.allowedWalls)
    : null;
  if (selectedShape) return strategy === selectedShape;
  switch (strategy) {
    case 'single-wall': return width >= 1800;
    case 'l-shape': return width >= 2400 && depth >= 2100;
    case 'u-shape': return width >= 2400 && depth >= 2400;
    case 'galley': return width >= 2400 && depth >= 2400;
  }
}

function canFitIsland(brief: DesignBrief): boolean {
  return brief.room.depth >= 3800 && brief.room.width >= 3200;
}

/** Structural signature: wall → ordered cabinet roles, plus island features. */
function fingerprintOf(spec: KitchenSpec): string {
  const runs = spec.runs
    .map(run => `${run.wall}:${run.segments
      .map(s => (s.kind === 'cabinet' ? s.role : s.kind))
      .join(',')}${run.wallCabinets ? '+w' : ''}`)
    .sort()
    .join('|');
  const island = spec.island ? `#island:${[...spec.island.features].sort().join(',')}` : '';
  return runs + island;
}

/** Storage variant: lean the deterministic layout toward storage capacity. */
function storageVariant(brief: DesignBrief, strategy: LayoutShape, style?: StyleSpec): KitchenSpec {
  const storageBrief: DesignBrief = {
    ...brief,
    priorities: brief.priorities.includes('storage') ? brief.priorities : [...brief.priorities, 'storage'],
  };
  const spec = defaultSpecFor(storageBrief, strategy, style);
  const runs = spec.runs.map(run => ({
    ...run,
    wallCabinets: true,
    // Storage-first should be visibly and functionally different: internal
    // drawers replace plain shelf cupboards wherever the role is flexible.
    segments: run.segments.map(segment =>
      segment.kind === 'cabinet' && segment.role === 'doors'
        ? seg('drawers', segment.widthMm)
        : { ...segment }),
  }));
  // Add a pantry to the longest practical run when the workflow layout did
  // not already include one. This may be dropped by the solver when it cannot
  // fit; compile + validate remain the authority.
  const hasPantry = runs.some(run => run.segments.some(segment =>
    segment.kind === 'cabinet' && segment.role === 'pantry'));
  const longest = runs
    .map((run, index) => ({ index, length: availableRunLength(brief, run.wall) }))
    .sort((a, b) => b.length - a.length || a.index - b.index)[0];
  if (!hasPantry && longest?.length >= 3000) runs[longest.index].segments.push(seg('pantry'));

  // Add one more drawer bank to the least-loaded run.
  const target = runs
    .map((run, index) => ({ index, load: run.segments.length }))
    .sort((a, b) => a.load - b.load || a.index - b.index)[0];
  if (target) runs[target.index].segments.push(seg('drawers', 600));
  return { ...spec, runs, rationale: 'Storage-first layout: maximum drawers, pantry and overhead cabinets.' };
}

function availableRunLength(brief: DesignBrief, wall: Wall): number {
  const range = rangeForWall(brief, wall);
  return range.endMm - range.startMm;
}

/** Social variant: island with seating where it fits, workflow otherwise. */
function socialVariant(brief: DesignBrief, strategy: LayoutShape, style?: StyleSpec): KitchenSpec | null {
  if (!canFitIsland(brief) || strategy === 'galley') return null;
  const socialBrief: DesignBrief = { ...brief, island: 'want' };
  const spec = defaultSpecFor(socialBrief, strategy, style);
  if (!spec.island) return null;
  return {
    ...spec,
    island: { ...spec.island, features: ['storage', 'seating'] },
    rationale: 'Entertainer layout: an island with seating keeps guests part of the conversation while you cook.',
  };
}

/** Sink-wall alternative for l/u strategies: mirror the side runs. */
function mirrorSideRuns(spec: KitchenSpec, brief: DesignBrief): KitchenSpec | null {
  const flip: Partial<Record<Wall, Wall>> = { W: 'E', E: 'W' };
  const allowed = brief.allowedWalls?.length ? new Set(brief.allowedWalls) : null;
  let changed = false;
  const runs = spec.runs.map(run => {
    const target = flip[run.wall];
    if (!target) return run;
    if (allowed && !allowed.has(target)) return run;
    changed = true;
    const { startMm: _startMm, endMm: _endMm, ...rest } = run;
    const selectedRange = brief.wallRanges?.[target];
    return {
      ...rest,
      wall: target,
      fromEnd: target === 'W',
      ...(selectedRange ? rangeForWall(brief, target) : {}),
    };
  });
  if (!changed) return null;
  return { ...spec, runs, rationale: `${spec.rationale} (mirrored to the opposite side wall.)` };
}

/**
 * Swap the sink and cooking zones between two runs while keeping the
 * dishwasher with the sink. This gives the customer a materially different
 * workflow to compare without allowing AI to invent unchecked geometry.
 */
function swapWorkZones(spec: KitchenSpec): KitchenSpec | null {
  const sinkRunIndex = spec.runs.findIndex(run => run.segments.some(segment =>
    segment.kind === 'cabinet' && segment.role === 'sink'));
  const cooktopRunIndex = spec.runs.findIndex(run => run.segments.some(segment =>
    segment.kind === 'cabinet' && segment.role === 'cooktop'));
  if (sinkRunIndex < 0 || cooktopRunIndex < 0 || sinkRunIndex === cooktopRunIndex) return null;

  const hadDishwasher = spec.runs[sinkRunIndex].segments.some(segment =>
    segment.kind === 'cabinet' && segment.role === 'dishwasher');
  const runs = spec.runs.map(run => ({ ...run, segments: [...run.segments] }));

  runs[sinkRunIndex].segments = runs[sinkRunIndex].segments.flatMap(segment => {
    if (segment.kind !== 'cabinet') return [segment];
    if (segment.role === 'sink') return [seg('cooktop', segment.widthMm)];
    if (segment.role === 'dishwasher') return [seg('doors', segment.widthMm)];
    return [segment];
  });

  runs[cooktopRunIndex].segments = runs[cooktopRunIndex].segments.flatMap(segment => {
    if (segment.kind !== 'cabinet' || segment.role !== 'cooktop') return [segment];
    return [seg('sink', segment.widthMm), ...(hadDishwasher ? [seg('dishwasher')] : [])];
  });

  return {
    ...spec,
    runs,
    rationale: 'Alternative workflow: sink and cooking zones change walls so you can compare plumbing, preparation space and walking distance.',
  };
}

interface Attempt {
  candidateId: string;
  strategy: LayoutShape;
  emphasis: CandidateEmphasis;
  spec: KitchenSpec;
}

export function generateCandidatePool(input: GenerateCandidatesInput): CandidatePool {
  const { brief, style } = input;
  const allowed = (input.allowedStrategies ?? ALL_STRATEGIES)
    .filter(s => ALL_STRATEGIES.includes(s));
  const maxCandidates = input.maxCandidates ?? 3;

  const attempted: LayoutShape[] = [];
  const attempts: Attempt[] = [];
  for (const strategy of allowed) {
    if (!strategyPlausible(strategy, brief)) continue;
    attempted.push(strategy);

    const workflow = defaultSpecFor(brief, strategy, style);
    attempts.push({ candidateId: `${strategy}/workflow`, strategy, emphasis: 'workflow', spec: workflow });

    const mirrored = mirrorSideRuns(workflow, brief);
    if (mirrored) {
      attempts.push({ candidateId: `${strategy}/workflow-mirrored`, strategy, emphasis: 'workflow', spec: mirrored });
    }

    const swappedZones = swapWorkZones(workflow);
    if (swappedZones) {
      attempts.push({ candidateId: `${strategy}/work-zones-swapped`, strategy, emphasis: 'workflow', spec: swappedZones });
    }

    attempts.push({
      candidateId: `${strategy}/storage`, strategy, emphasis: 'storage',
      spec: storageVariant(brief, strategy, style),
    });

    const social = socialVariant(brief, strategy, style);
    if (social) attempts.push({ candidateId: `${strategy}/social`, strategy, emphasis: 'social', spec: social });
  }

  const candidates: DesignCandidate[] = [];
  const rejected: RejectedCandidate[] = [];
  for (const attempt of attempts) {
    let compiled;
    try {
      compiled = compileSpec(attempt.spec, brief.room);
    } catch (err) {
      rejected.push({
        candidateId: attempt.candidateId, strategy: attempt.strategy, emphasis: attempt.emphasis,
        reasons: [err instanceof Error ? err.message : 'compile failed'],
      });
      continue;
    }
    const violations = validate(compiled, brief.room, brief);
    const errors = violations.filter(v => v.severity === 'error');
    if (errors.length > 0) {
      rejected.push({
        candidateId: attempt.candidateId, strategy: attempt.strategy, emphasis: attempt.emphasis,
        reasons: errors.map(e => `${e.code}: ${e.message}`),
      });
      continue;
    }
    const band = priceDesign(compiled.items, attempt.spec.style);
    candidates.push({
      candidateId: attempt.candidateId,
      strategy: attempt.strategy,
      emphasis: attempt.emphasis,
      spec: attempt.spec,
      items: compiled.items,
      violations,
      priceBand: { lowAud: band.lowAud, highAud: band.highAud },
      score: scoreDesign(brief, attempt.spec, violations),
      fingerprint: fingerprintOf(attempt.spec),
    });
  }

  // De-duplicate structurally identical candidates, keeping the best score.
  const byFingerprint = new Map<string, DesignCandidate>();
  for (const c of candidates) {
    const existing = byFingerprint.get(c.fingerprint);
    if (!existing || c.score.total > existing.score.total) byFingerprint.set(c.fingerprint, c);
  }

  // Rank, then pick with diversity: a new pick must add a new strategy or a
  // new emphasis; never a colour-level variation of an already-picked design.
  const ranked = [...byFingerprint.values()].sort((a, b) =>
    b.score.total - a.score.total || a.candidateId.localeCompare(b.candidateId));
  const picked: DesignCandidate[] = [];
  for (const c of ranked) {
    if (picked.length >= maxCandidates) break;
    const diverse = picked.every(p => p.strategy !== c.strategy || p.emphasis !== c.emphasis);
    if (diverse) picked.push(c);
  }
  // backfill if diversity left slots empty
  for (const c of ranked) {
    if (picked.length >= maxCandidates) break;
    if (!picked.includes(c)) picked.push(c);
  }

  return { candidates: picked, rejected, attemptedStrategies: attempted };
}

/** Compact summary for AI ranking prompts (§8.4): no geometry, no items. */
export function candidateSummaryFor(candidate: DesignCandidate): {
  candidateId: string;
  strategy: LayoutShape;
  emphasis: CandidateEmphasis;
  score: number;
  scoreParts: DesignScore['parts'];
  priceBand: { lowAud: number; highAud: number };
  cabinetRoles: string[];
  island: string[] | null;
  warnings: string[];
} {
  return {
    candidateId: candidate.candidateId,
    strategy: candidate.strategy,
    emphasis: candidate.emphasis,
    score: candidate.score.total,
    scoreParts: candidate.score.parts,
    priceBand: candidate.priceBand,
    cabinetRoles: candidate.spec.runs.flatMap(r =>
      r.segments.flatMap(s => (s.kind === 'cabinet' ? [`${r.wall}:${s.role}`] : []))),
    island: candidate.spec.island ? [...candidate.spec.island.features] : null,
    warnings: candidate.violations.filter(v => v.severity === 'warn').map(v => v.message),
  };
}
