// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/layout instead.
// Pure type/module file. No runtime side effects.

export type ItemType = 'Cabinet' | 'Wall' | 'Structure' | 'Appliance';
export type CabinetType = 'Base' | 'Wall' | 'Tall';

export interface CatalogItemDefinition {
  id: string;
  sku: string;
  name: string;
  itemType: ItemType;
  category?: CabinetType;
  defaultWidth: number;
  defaultDepth: number;
  defaultHeight: number;
  price: number;
}

export type HandingOverride = 'Auto' | 'L' | 'R';

export interface PlacedItem {
  instanceId: string;
  definitionId: string;
  itemType: ItemType;

  // Locked cabinet reference (C01, C02...) stored ON the item.
  cabinetNumber?: string;

  x: number;
  y: number;
  z: number;
  rotation: number;
  width: number;
  depth: number;
  height: number;

  // Cabinet intent options
  handingOverride?: HandingOverride;
  endPanelLeft?: boolean;
  endPanelRight?: boolean;
  /** Dishwasher/appliance openings: render benchtop-support top rails.
   *  Defaults to on (undefined) — set false to leave the opening topless. */
  topRail?: boolean;
  fillerLeft?: number;
  fillerRight?: number;

  finishColor?: string;
  /** carcase board material (id/item_code/name) for piece pricing */
  carcaseMaterialId?: string;
  /** exterior/door finish material (id/item_code/name) for piece pricing */
  exteriorMaterialId?: string;
  /** selected edge banding (id/item_code/name) — priced by edgeCalculator */
  edgeId?: string;
  /** supplier finish image URLs for the 3D texture (resolved outside the canvas) */
  doorTextureUrl?: string | null;
  carcaseTextureUrl?: string | null;
  handleType?: string;
  /** UI finish swatch id for the handle colour (e.g. 'matte-black') */
  handleColor?: string;
  hinge?: 'Left' | 'Right';
  blindSide?: 'Left' | 'Right';
  panelOverhang?: number;
  rightCarcaseDepth?: number;
  leftCarcaseDepth?: number;
  secondWidth?: number;        // corner SECOND wall run (Wall 2) in mm; width = Wall 1
  shelfCount?: number;         // adjustable shelf count from the editor (overrides recipe default)
  drawerFrontHeights?: number[]; // mm, top → bottom — custom drawer face heights (overrides standard distribution)
  tapId?: string;
  applianceId?: string;
  
  // Corner cabinet configuration (Phase 3)
  cornerFillerWidth?: number;   // Gap between blind panel and wall (mm)
  cornerStileWidth?: number;    // Face frame stile width (mm)
  blindPullDistance?: number;   // How far blind extends past face (mm)
}

export type RoomShape = 'Rectangle' | 'LShape';

/** Wall identifier, viewed in plan: N = back wall, S = front, W = left, E = right. */
export type WallId = 'N' | 'E' | 'S' | 'W';

/** A door, window, or open walkway in a wall. Offsets measured in mm from the
 *  wall's left corner when facing the wall from inside the room. */
export interface Opening {
  id: string;
  wall: WallId;
  type: 'door' | 'window' | 'walkway';
  offsetMm: number;
  widthMm: number;
  /** door/window height (mm). Defaults: door 2040, window 1200. */
  heightMm?: number;
  /** windows only — floor to sill (mm). Default 900. */
  sillHeightMm?: number;
  /** doors only — drives swing-arc clearance validation. */
  swing?: 'in-left' | 'in-right' | 'out' | 'slider';
}

/** Fixed service location (plumbing / power / gas / ducting) on a wall. */
export interface ServicePoint {
  id: string;
  wall: WallId;
  type: 'water-supply' | 'drain' | 'gpo' | 'gas' | 'hood-duct';
  offsetMm: number;
  /** height above floor (mm), e.g. GPO at 1050. */
  heightMm?: number;
}

export interface RoomConfig {
  width: number;
  depth: number;
  height: number;
  shape: RoomShape;
  cutoutWidth: number;
  cutoutDepth: number;
  /** Doors/windows/walkways. Optional — legacy designs have none. */
  openings?: Opening[];
  /** Plumbing/power/gas points. Optional — legacy designs have none. */
  services?: ServicePoint[];
}

export type TextureType = 'none' | 'wood' | 'stone' | 'concrete' | 'marble';

export interface MaterialOption {
  id: string;
  name: string;
  hex: string;
  priceMultiplier: number;
  textureType?: TextureType;
  roughness?: number;
  metalness?: number;
}

/** Visual handle styles renderable by HandleMesh. */
export type HandleType = 'Bar' | 'DPull' | 'Knob' | 'Cup' | 'Lip' | 'Flush' | 'Profile' | 'None';

export interface HandleDefinition {
  id: string;
  name: string;
  type: HandleType;
  hex: string;
  price: number;
  /** True when the product's material fixes its colour (brass, wood…) so the
   *  user's chosen handle finish should NOT override it. */
  finishLocked?: boolean;
}

export interface TapDefinition {
  id: string;
  name: string;
  type: 'Mixer' | 'Gooseneck' | 'Square';
  hex: string;
}

export interface ApplianceModel {
  id: string;
  name: string;
  type: 'Oven' | 'Microwave';
  hex: string;
}

export interface ProjectSettings {
  userRole?: 'standard' | 'trade';
  jobName: string;
  jobReference: string;
  contactNumber: string;
  description: string;
  deliveryMethod: 'pickup' | 'delivery';
}

export interface GlobalDimensions {
  toeKickHeight: number;
  shelfSetback: number;
  baseHeight: number;
  baseDepth: number;
  wallHeight: number;
  wallDepth: number;
  tallHeight: number;
  tallDepth: number;
  benchtopThickness: number;
  benchtopOverhang: number;
  splashbackHeight: number;
  /** Floor-to-underside mounting height for wall cabinets (mm). Default 1350. */
  wallMountHeight: number;


  doorGap: number;
  drawerGap: number;
  leftGap: number;
  rightGap: number;
  topMargin: number;
  bottomMargin: number;

  /** Gap between cabinet back and wall for installation tolerance (mm) */
  wallGap: number;

  // Construction parameters (Microvellum-style)
  /** Board thickness for gables/shelves (mm) - typically 16, 18, 25, 32 */
  boardThickness: number;
  /** Back panel setback for hanging rails (mm) - typically 16 */
  backPanelSetback: number;
  /** Top reveal gap above doors (mm) - typically 3 */
  topReveal: number;
  /** Side reveal gap beside doors (mm) - typically 2 */
  sideReveal: number;
  /** 32mm system handle drill spacing (mm) - 32, 64, 96, 128 */
  handleDrillSpacing: number;

  // Corner cabinet defaults
  /** Default filler width for blind corner cabinets (mm) */
  cornerFillerWidth?: number;
  /** Default stile width for corner cabinets (mm) */
  cornerStileWidth?: number;
}

export interface HardwareOptions {
  hingeType: string;
  drawerType: string;
  cabinetTop: string;
  supplyHardware: boolean;
  adjustableLegs: boolean;
  handleId: string;
  /** UI finish swatch id (e.g. 'matte-black') applied to the handle colour. */
  handleColor?: string;
}


export const WALL_THICKNESS = 200;
export const SNAP_INCREMENT = 50;

// Static catalog removed - now using Microvellum products exclusively from database
// See src/hooks/useCatalog.ts for dynamic catalog loading

export const FINISH_OPTIONS: MaterialOption[] = [
  { id: 'do-designer-white', name: 'Designer White', hex: '#fcfcfc', priceMultiplier: 1.0, textureType: 'none', roughness: 0.2, metalness: 0.0 },
  { id: 'do-classic-white', name: 'Classic White', hex: '#f4f4f4', priceMultiplier: 1.0, textureType: 'none', roughness: 0.2, metalness: 0.0 },
  { id: 'do-stone-grey', name: 'Stone Grey', hex: '#8c8c8c', priceMultiplier: 1.0, textureType: 'none', roughness: 0.4, metalness: 0.0 },
  { id: 'do-charcoal', name: 'Charcoal', hex: '#363636', priceMultiplier: 1.0, textureType: 'none', roughness: 0.5, metalness: 0.0 },
  { id: 'do-black', name: 'Black', hex: '#1a1a1a', priceMultiplier: 1.1, textureType: 'none', roughness: 0.5, metalness: 0.0 },
  { id: 'do-natural-oak', name: 'Natural Oak', hex: '#d4c2a5', priceMultiplier: 1.2, textureType: 'wood', roughness: 0.6, metalness: 0.0 },
  { id: 'do-spotted-gum', name: 'Spotted Gum', hex: '#ac8868', priceMultiplier: 1.2, textureType: 'wood', roughness: 0.6, metalness: 0.0 },
  { id: 'do-natural-walnut', name: 'Natural Walnut', hex: '#5d4037', priceMultiplier: 1.2, textureType: 'wood', roughness: 0.6, metalness: 0.0 },
];

export const BENCHTOP_OPTIONS: MaterialOption[] = [
  { id: 'egger-premium-white', name: 'Premium White (W1000)', hex: '#ffffff', priceMultiplier: 1.0, textureType: 'none', roughness: 0.1, metalness: 0.0 },
  { id: 'egger-white-carrara', name: 'White Carrara Marble (F204)', hex: '#ebebeb', priceMultiplier: 1.1, textureType: 'marble', roughness: 0.1, metalness: 0.1 },
  { id: 'egger-concrete-chicago-light', name: 'Light Chicago Concrete (F186)', hex: '#b0b0b0', priceMultiplier: 1.1, textureType: 'concrete', roughness: 0.8, metalness: 0.0 },
  { id: 'egger-concrete-chicago-dark', name: 'Dark Chicago Concrete (F187)', hex: '#595959', priceMultiplier: 1.1, textureType: 'concrete', roughness: 0.8, metalness: 0.0 },
  { id: 'egger-halifax-oak-nat', name: 'Natural Halifax Oak (H1180)', hex: '#d6c5a6', priceMultiplier: 1.2, textureType: 'wood', roughness: 0.6, metalness: 0.0 },
  { id: 'egger-black', name: 'Black (U999)', hex: '#1a1a1a', priceMultiplier: 1.1, textureType: 'none', roughness: 0.2, metalness: 0.0 },
];

export const KICK_OPTIONS: MaterialOption[] = [
  { id: 'kick-stainless', name: 'Brushed Stainless', hex: '#e5e7eb', priceMultiplier: 0, roughness: 0.3, metalness: 0.9, textureType: 'none' },
  { id: 'kick-brass', name: 'Brushed Brass', hex: '#fcd34d', priceMultiplier: 0, roughness: 0.3, metalness: 0.8, textureType: 'none' },
  { id: 'kick-black', name: 'Matte Black', hex: '#111827', priceMultiplier: 0, roughness: 0.8, metalness: 0.0, textureType: 'none' },
  { id: 'kick-white', name: 'White Satin', hex: '#ffffff', priceMultiplier: 0, roughness: 0.3, metalness: 0.0, textureType: 'none' },
];

export const TAP_OPTIONS: TapDefinition[] = [
  { id: 'tap-chrome', name: 'Chrome Mixer', type: 'Mixer', hex: '#e5e7eb' },
  { id: 'tap-goose-bk', name: 'Black Gooseneck', type: 'Gooseneck', hex: '#1a1a1a' },
  { id: 'tap-goose-ss', name: 'Brushed Gooseneck', type: 'Gooseneck', hex: '#9ca3af' },
];

export const APPLIANCE_MODELS: ApplianceModel[] = [
  { id: 'oven-hafele-600-ss', name: 'Hafele 600mm Oven (SS)', type: 'Oven', hex: '#d1d5db' },
  { id: 'oven-hafele-600-blk', name: 'Hafele 600mm Oven (Black)', type: 'Oven', hex: '#1a1a1a' },
  { id: 'mw-hafele-600-ss', name: 'Hafele Built-in Microwave (SS)', type: 'Microwave', hex: '#d1d5db' },
];

export const HANDLE_OPTIONS: HandleDefinition[] = [
  { id: 'handle-bar-ss', name: 'Stainless Bar', type: 'Bar', hex: '#d1d5db', price: 15 },
  { id: 'handle-bar-bk', name: 'Matte Black Bar', type: 'Bar', hex: '#1f2937', price: 15 },
  { id: 'handle-bar-go', name: 'Brushed Gold Bar', type: 'Bar', hex: '#d4af37', price: 25 },
  { id: 'handle-knob-ss', name: 'Stainless Knob', type: 'Knob', hex: '#d1d5db', price: 10 },
  { id: 'handle-lip-ss', name: 'Lip Pull Silver', type: 'Lip', hex: '#e5e7eb', price: 12 },
  { id: 'handle-none', name: 'Push to Open', type: 'None', hex: 'transparent', price: 0 },
];

export const HINGE_OPTIONS = ['Blum Inserta Soft Close', 'Blum Standard', 'Hettich Sensys', 'Generic Soft Close'];
export const DRAWER_OPTIONS = ['Hafele Alto Slim', 'Blum Antaro', 'Hettich InnoTech', 'Generic Metal Box'];

export const DEFAULT_GLOBAL_DIMENSIONS: GlobalDimensions = {
  toeKickHeight: 135,
  shelfSetback: 5,
  baseHeight: 730,
  baseDepth: 575,
  wallHeight: 720,
  wallDepth: 350,
  tallHeight: 2100,
  tallDepth: 580,
  benchtopThickness: 33,
  benchtopOverhang: 25,
  splashbackHeight: 600,
  wallMountHeight: 1350,       // Standard floor-to-underside of wall cabinet
  doorGap: 2,
  drawerGap: 2,
  leftGap: 1.5,
  rightGap: 1.5,
  topMargin: 0,
  bottomMargin: 0,
  wallGap: 10,
  
  // Construction parameters (Microvellum-style defaults)
  boardThickness: 16,        // MV-verified 16mm board
  backPanelSetback: 16,      // 16mm setback for hanging rails
  topReveal: 1,              // MV-verified (door height = carcass − 2)
  sideReveal: 1,             // MV-verified (door/front width = cabinet − 2)
  handleDrillSpacing: 32,    // 32mm system
  
  // Corner cabinet defaults
  cornerFillerWidth: 75,     // 75mm filler for blind corners
  cornerStileWidth: 45,      // 45mm face frame stile
};
