// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/layout instead.
/**
 * Professional deterministic score for rule-approved candidate layouts.
 * The six categories and their weights are the v5 release contract.
 */

import { ROLE_PRODUCTS } from './catalogRoles.ts';
import { styleProfile } from './styleDNA.ts';
import type { DesignBrief, KitchenSpec, Segment, SegmentRole, Violation } from './types.ts';

export interface DesignScoreParts {
  workflow: number;       // 0-30
  preparation: number;    // 0-20
  spaceAndCorners: number;// 0-15
  storage: number;        // 0-15
  styleFidelity: number;  // 0-15
  services: number;       // 0-5
}

export interface DesignScore {
  total: number;
  parts: DesignScoreParts;
  meetsMinimum: boolean;
  failedMinimums: string[];
}

export const PROFESSIONAL_SCORE_MINIMUM = 80;
export const PROFESSIONAL_CATEGORY_MINIMUMS: Readonly<Record<keyof DesignScoreParts, number>> = Object.freeze({
  workflow: 24,
  preparation: 16,
  spaceAndCorners: 12,
  storage: 8,
  styleFidelity: 12,
  services: 0,
});

const BASE_ROLES = new Set<SegmentRole>(['sink', 'cooktop', 'drawers', 'doors', 'dishwasher', 'corner-buffer']);

function widthOf(segment: Segment): number {
  if (segment.kind !== 'cabinet') return segment.widthMm;
  return segment.widthMm ?? ROLE_PRODUCTS[segment.role]?.widths[0] ?? 600;
}

function longestBenchStretch(spec: KitchenSpec): number {
  let best = 0;
  for (const run of spec.runs) {
    let current = 0;
    for (const segment of run.segments) {
      if (segment.kind === 'cabinet' && BASE_ROLES.has(segment.role)) {
        current += widthOf(segment);
        best = Math.max(best, current);
      } else {
        current = 0;
      }
    }
  }
  return best;
}

function roleCount(spec: KitchenSpec, role: SegmentRole): number {
  return spec.runs.reduce((total, run) => total + run.segments.filter(
    segment => segment.kind === 'cabinet' && segment.role === role,
  ).length, 0);
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, Math.round(value)));
}

export function scoreDesign(
  brief: DesignBrief,
  spec: KitchenSpec,
  violations: Violation[],
): DesignScore {
  const codes = new Set(violations.map(violation => violation.code));

  let workflow = 30;
  if (codes.has('triangle-size')) workflow -= 8;
  // A long individual leg is a quality warning, not a dead-end by itself.
  // The total triangle size and blocked paths remain hard presentation gates.
  if (codes.has('triangle-leg')) workflow -= 6;
  if (codes.has('triangle-obstruction')) workflow -= 10;
  if (codes.has('cooktop-landing')) workflow -= 8;
  if (codes.has('cooktop-window')) workflow -= 4;
  if (codes.has('sink-side-clearance')) workflow -= 2;
  if (codes.has('fridge-landing')) workflow -= 6;
  if (codes.has('dishwasher-not-adjacent')) workflow -= 10;
  if (codes.has('tall-unit-run-end') || codes.has('tall-unit-workflow-break')) workflow -= 12;
  workflow = clamp(workflow, 0, 30);

  const stretch = longestBenchStretch(spec);
  let preparation = stretch >= 1800 ? 20 : stretch >= 1200 ? 18 : stretch >= 900 ? 16 : 8;
  if (codes.has('prep-space')) preparation = 0;
  preparation = clamp(preparation, 0, 20);

  let spaceAndCorners = 15;
  if (codes.has('corner-resolution') || codes.has('corner-integrity')) spaceAndCorners -= 8;
  if (codes.has('narrow-aisle') || codes.has('narrow-galley')) spaceAndCorners -= 8;
  if (codes.has('overlap') || codes.has('out-of-room')) spaceAndCorners = 0;
  spaceAndCorners = clamp(spaceAndCorners, 0, 15);

  const drawers = roleCount(spec, 'drawers');
  const doors = roleCount(spec, 'doors');
  const pantry = roleCount(spec, 'pantry');
  const upperCoverage = spec.runs.reduce((sum, run) => sum + (run.upperPlan?.coverageRatio ?? (run.wallCabinets ? 1 : 0)), 0)
    / Math.max(1, spec.runs.length);
  let storage = 7 + Math.min(4, drawers * 1.5) + Math.min(2, doors * .5) + Math.min(3, pantry * 3) + Math.min(2, upperCoverage * 2);
  if (brief.priorities.includes('storage') && pantry === 0 && drawers < 2) storage -= 3;
  storage = clamp(storage, 0, 15);

  const profile = styleProfile(spec.style.familyId);
  let styleFidelity = profile ? 15 : 12;
  if (codes.has('style-required-feature')) styleFidelity -= 8;
  if (codes.has('style-overhead-density')) styleFidelity -= 7;
  if (codes.has('style-open-shelving')) styleFidelity -= 7;
  styleFidelity = clamp(styleFidelity, 0, 15);

  let services = 5;
  if (codes.has('replumb')) services -= 3;
  if (codes.has('gas-move')) services -= 2;
  services = clamp(services, 0, 5);

  const parts: DesignScoreParts = { workflow, preparation, spaceAndCorners, storage, styleFidelity, services };
  const total = Object.values(parts).reduce((sum, value) => sum + value, 0);
  const failedMinimums = (Object.keys(PROFESSIONAL_CATEGORY_MINIMUMS) as (keyof DesignScoreParts)[])
    .filter(key => parts[key] < PROFESSIONAL_CATEGORY_MINIMUMS[key]);
  return {
    total,
    parts,
    meetsMinimum: total >= PROFESSIONAL_SCORE_MINIMUM && failedMinimums.length === 0,
    failedMinimums,
  };
}

export function meetsProfessionalThreshold(score: DesignScore): boolean {
  return score.meetsMinimum;
}
