// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/layout instead.
/**
 * AI Kitchen Designer — deterministic layout engine.
 * The harness: the AI writes KitchenSpec; this engine compiles, validates,
 * and prices it. Pure TS — safe to bundle for the browser, node tests, and
 * the Supabase edge function.
 */

export * from './types.ts';
export * from './schemas.ts';
export * from './geometry.ts';
export * from './catalogRoles.ts';
export { solveRun } from './solveRun.ts';
export { compileSpec, type CompiledDesign } from './compileSpec.ts';
export { validate } from './validate.ts';
export {
  polygonFromRoom,
  segmentToWorld,
  pointInPolygon,
  rectInsidePolygon,
  rotationFromNormal,
  interiorAngles,
  type Vec2,
  type WallSegment,
  type RoomPolygon,
  type CutoutCorner,
} from './polygon.ts';
export {
  evaluateRules,
  ruleWhy,
  RULES,
  RULE_INDEX,
  RESERVED_RULE_IDS,
  type Rule,
  type RuleTier,
  type RuleScope,
  type RuleFinding,
  type RuleContext,
} from './rules.ts';
export { defaultSpecFor, type LayoutShape } from './defaultSpec.ts';
export { priceDesign } from './priceDesign.ts';
export { toRoomSpec, briefFromWizard } from './wizardAdapter.ts';
export { scoreDesign, type DesignScore, type DesignScoreParts } from './designScore.ts';
export {
  generateCandidatePool,
  candidateSummaryFor,
  type CandidateEmphasis,
  type CandidatePool,
  type DesignCandidate,
  type GenerateCandidatesInput,
  type RejectedCandidate,
} from './candidateGenerator.ts';
export {
  RequestProposalRegistry,
  type ProposalSelection,
  type ProposalSelectionResult,
  type RegisteredProposal,
} from './proposalState.ts';
