// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/layout instead.
/**
 * AI Kitchen Designer — deterministic layout engine.
 * The harness: the AI writes KitchenSpec; this engine compiles, validates,
 * and prices it. Pure TS — safe to bundle for the browser, node tests, and
 * the Supabase edge function.
 */

export * from './types.ts';
export * from './schemas.ts';
export * from './geometry.ts';
export * from './catalogRoles.ts';
export { solveRun } from './solveRun.ts';
export { compileSpec, type CompiledDesign } from './compileSpec.ts';
export { validate } from './validate.ts';
export { defaultSpecFor, type LayoutShape } from './defaultSpec.ts';
export { priceDesign } from './priceDesign.ts';
export { toRoomSpec, briefFromWizard } from './wizardAdapter.ts';
