// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/layout instead.
/** Public, read-only boundary for provisional RoomDocument wall-run ideas.
 * The same parser and candidate engine are copied into the Edge runtime.
 * No KitchenSpec, price or confirmed whole-room design is returned here. */
import { z } from 'npm:zod@3.25.76';
import type { RoomDocumentV1 } from '../roomDocument/index.ts';
import { generateRoomDocumentCandidates, type RoomDocumentCandidatePool } from './roomDocumentCandidates.ts';
import type { StyleSpec } from './types.ts';

const id = z.string().min(1).max(128);
const mm = z.number().finite().min(0).max(1_000_000);
const coordinate = z.number().finite().min(-1_000_000).max(1_000_000);
const dimension = z.object({
  valueMm: z.number().finite(),
  source: z.enum(['measured', 'observed', 'inferred', 'unknown']),
  uncertaintyMm: mm.optional(),
  evidenceIds: z.array(id).max(64).optional(),
  reason: z.string().max(1000).optional(),
}).passthrough();
const placement = z.discriminatedUnion('type', [
  z.object({ type: z.literal('wall'), wallId: id, offsetMm: coordinate, depthOffsetMm: coordinate.optional() }),
  z.object({ type: z.literal('free'), xMm: coordinate, zMm: coordinate, rotationDeg: z.number().finite() }),
]);
const documentSchema = z.object({
  version: z.literal(1), id, revision: z.number().int().min(0), name: z.string().max(200).optional(),
  corners: z.array(z.object({ id, xMm: coordinate, zMm: coordinate })).max(64),
  walls: z.array(z.object({
    id, startCornerId: id, endCornerId: id,
    interiorSide: z.enum(['left', 'right', 'unknown']).optional(),
    height: dimension.optional(), lengthEvidence: dimension.optional(),
    evidenceIds: z.array(id).max(64).optional(),
  })).max(48),
  chains: z.array(z.object({ id, wallIds: z.array(id).max(48), closed: z.boolean() })).max(16),
  floorBoundary: z.object({ cornerIds: z.array(id).max(64), confirmed: z.literal(true) }).passthrough().optional(),
  openings: z.array(z.object({
    id, wallId: id, kind: z.enum(['door', 'window', 'walkway']),
    offsetMm: coordinate, widthMm: mm, heightMm: mm.optional(), sillHeightMm: mm.optional(),
    revealMm: mm.optional(), swing: z.enum(['in-left', 'in-right', 'out', 'slider']).optional(),
    benchtopObjectId: id.optional(),
    benchtopRelationship: z.enum(['above', 'behind', 'intersects', 'through-reveal', 'unknown']).optional(),
  }).passthrough()).max(128),
  services: z.array(z.object({
    id, kind: z.enum(['water-supply', 'drain', 'gpo', 'gas', 'hood-duct', 'light', 'fan', 'other']),
    placement, heightMm: mm.optional(),
  }).passthrough()).max(128),
  objects: z.array(z.object({
    id, layer: z.enum(['existing', 'proposed']), kind: z.string().min(1).max(100), placement,
    widthMm: mm, depthMm: mm, heightMm: mm.optional(), elevationMm: mm.optional(),
    catalogueId: id.optional(), sourceCabinetId: id.optional(),
    existingAction: z.enum(['keep', 'remove', 'relocate']).optional(),
    sizeLock: z.enum(['none', 'confirmed', 'catalogue']).optional(),
  }).passthrough()).max(256),
}).passthrough();
const styleSchema = z.object({ finishId: id, benchtopId: id, handleId: id }).passthrough();
const requestSchema = z.object({
  document: documentSchema,
  style: styleSchema.optional(),
  allowedWallIds: z.array(id).max(48).optional(),
  maxCandidates: z.number().int().min(1).max(8).optional(),
});

export type RoomDocumentCandidateApiResult =
  | { ok: true; status: 'preliminary'; roomId: string; roomRevision: number; pool: RoomDocumentCandidatePool }
  | { ok: false; error: 'invalid_room_document_request' };

/** Fail closed on malformed or unreasonably large plans. Absolute coordinates
 * may be arbitrary, but an automatic island search is capped to a 16 m span. */
export function evaluateRoomDocumentCandidateRequest(body: unknown): RoomDocumentCandidateApiResult {
  const parsed = requestSchema.safeParse(body);
  if (!parsed.success) return { ok: false, error: 'invalid_room_document_request' };
  const { document, style, allowedWallIds, maxCandidates } = parsed.data;
  const x = document.corners.map(corner => corner.xMm);
  const zValues = document.corners.map(corner => corner.zMm);
  if (x.length && (Math.max(...x) - Math.min(...x) > 16_000
    || Math.max(...zValues) - Math.min(...zValues) > 16_000)) {
    return { ok: false, error: 'invalid_room_document_request' };
  }
  try {
    return {
      ok: true, status: 'preliminary', roomId: document.id, roomRevision: document.revision,
      pool: generateRoomDocumentCandidates({
        document: document as RoomDocumentV1,
        ...(style ? { style: style as StyleSpec } : {}),
        ...(allowedWallIds ? { allowedWallIds } : {}),
        ...(maxCandidates ? { maxCandidates } : {}),
      }),
    };
  } catch {
    return { ok: false, error: 'invalid_room_document_request' };
  }
}
