// GENERATED by scripts/sync-ai-shared.mjs — edit src/lib/layout instead.
/**
 * rules — the kitchen rules engine (relational tier).
 *
 * Every design check is a declarative Rule object with a TIER and a SCOPE.
 * `validate()` (validate.ts) runs this registry and maps findings back to the
 * legacy Violation contract, so the registry is now the single source of truth
 * for "is this design any good" without changing any caller.
 *
 * TIERS (the taxonomy the product roadmap asks for):
 *   - 'hard'   → the design is invalid; the candidate is rejected (→ Violation
 *                severity 'error'). These are the checks that were errors before.
 *   - 'safety' → the design works but has a real problem a person should fix or
 *                accept (→ 'warn', surfaced prominently). "Require correction."
 *   - 'soft'   → a preference/quality signal that influences ranking, never
 *                blocks (→ 'warn'). designScore.ts consumes the soft signals.
 *
 * SCOPE tags each rule 'relational' (role/topology — valid on today's model and
 * across the coming polygon-geometry change) or 'spatial' (queries coordinates;
 * to be re-implemented against the room polygon in the geometry phase). The tag
 * exists so the geometry migration knows exactly which rules to revisit.
 *
 * Each rule also carries a plain-language `why` — the intent, reused by the
 * "explain this design" feature. Add a rule here, and it is automatically
 * enforced, sweep-enumerated (RULE_INDEX) and explainable.
 */

import type { PlacedItem } from './core.ts';
import { rangeForWall } from './briefConstraints.ts';
import {
  FRIDGE_ROOM_CORNER_CLEARANCE_MM,
  FRIDGE_SIDE_CLEARANCE_MM,
  fridgeOpeningWidthMm,
} from './catalogRoles.ts';
import { ROLE_PRODUCTS } from './catalogRoles.ts';
import { styleProfile } from './styleDNA.ts';
import {
  BLIND_CORNER_MIN_ACCESS_MM,
  BLIND_CORNER_RETURN_MM,
  blindCornerFrontLayout,
} from './blindCorner.ts';
import {
  benchtopRect, dist, itemRect, rectsJoin, rectsOverlap, sharedCornerAt, wallLength,
  servicePointWorld, wallPointWorld, WALL_ROTATION,
} from './geometry.ts';
import type { CompiledDesign } from './compileSpec.ts';
import type { DesignBrief, RoomSpec, Segment, SegmentRole, Wall } from './types.ts';

export type RuleTier = 'hard' | 'safety' | 'soft';
export type RuleScope = 'relational' | 'spatial';

export interface RuleFinding {
  ruleId: string;
  tier: RuleTier;
  /** customer/staff-facing description of the specific problem instance */
  message: string;
  itemIds?: string[];
}

export interface RuleContext {
  design: CompiledDesign;
  room: RoomSpec;
  brief?: DesignBrief;
  /** y===0 items (base/tall); computed once for every rule */
  floorItems: PlacedItem[];
  /** island cabinets (free-standing rows), computed once */
  islandItems: PlacedItem[];
}

export interface Rule {
  id: string;
  tier: RuleTier;
  scope: RuleScope;
  title: string;
  /** plain-language reason this rule exists — reused by design explanations */
  why: string;
  /** empty array = pass */
  evaluate(ctx: RuleContext): RuleFinding[];
}

// thresholds (mm) — shared with the legacy checks they replace
const MIN_AISLE = 900;
const MIN_FACING_AISLE = 900;
const TRIANGLE_MIN = 3600;
const TRIANGLE_MAX = 8000;
const LEG_MIN = 1200;
const LEG_MAX = 2700;
const SINK_DRAIN_MAX = 1500;
const GAS_MAX = 600;
/** Fallbacks only: the nominated appliance installation instructions govern. */
const GAS_COOKTOP_COMBUSTIBLE_SIDE_CLEARANCE = 200;
const INDUCTION_COOKTOP_SIDE_CLEARANCE_FALLBACK = 150;
const OVEN_TOWER_CORNER_CLEARANCE = 600;
const COOKTOP_LANDING_MIN = 300;
const SINK_SIDE_CLEARANCE_MIN = 300;
const FRIDGE_LANDING_MIN = 400;
const PREP_BENCH_MIN = 900;

function finding(ruleId: string, tier: RuleTier, message: string, itemIds?: string[]): RuleFinding {
  return { ruleId, tier, message, ...(itemIds ? { itemIds } : {}) };
}

const TALL_ROLES = new Set<SegmentRole>([
  'pantry', 'oven-tower', 'fridge-gap', 'fridge-corner-pantry',
]);
const BENCH_ROLES = new Set<SegmentRole>(['doors', 'drawers', 'dishwasher', 'corner-buffer']);

function segmentWidth(segment: Segment): number {
  if (segment.kind !== 'cabinet') return segment.widthMm;
  return segment.widthMm ?? ROLE_PRODUCTS[segment.role].widths[0] ?? 600;
}

function isBenchSegment(segment: Segment): boolean {
  return segment.kind === 'cabinet' && BENCH_ROLES.has(segment.role);
}

function isTallSegment(segment: Segment): boolean {
  return segment.kind === 'cabinet' && TALL_ROLES.has(segment.role);
}

function contiguousBenchFrom(segments: Segment[], start: number, direction: -1 | 1): number {
  let total = 0;
  for (let index = start; index >= 0 && index < segments.length; index += direction) {
    const segment = segments[index];
    if (!isBenchSegment(segment)) break;
    total += segmentWidth(segment);
  }
  return total;
}

function contiguousSinkSideFrom(segments: Segment[], start: number, direction: -1 | 1): number {
  let total = 0;
  for (let index = start; index >= 0 && index < segments.length; index += direction) {
    const segment = segments[index];
    if (segment.kind !== 'cabinet'
      || (!BENCH_ROLES.has(segment.role) && segment.role !== 'corner')) break;
    total += segmentWidth(segment);
  }
  return total;
}

function runTouchesSharedCorner(design: CompiledDesign, room: RoomSpec, a: Wall, b: Wall): boolean {
  const atA = sharedCornerAt(a, b);
  const atB = sharedCornerAt(b, a);
  if (!atA || !atB) return false;
  const rangeA = design.runRanges.find(range => range.wall === a);
  const rangeB = design.runRanges.find(range => range.wall === b);
  if (!rangeA || !rangeB) return false;
  const reaches = (range: { startMm: number; endMm: number }, wall: Wall, end: 'start' | 'end') =>
    end === 'start' ? range.startMm <= 25 : range.endMm >= wallLength(wall, room) - 25;
  return reaches(rangeA, a, atA) && reaches(rangeB, b, atB);
}

function segmentCrossesRect(
  start: { x: number; z: number },
  end: { x: number; z: number },
  rect: { minX: number; maxX: number; minZ: number; maxZ: number },
): boolean {
  // Liang-Barsky clipping with an endpoint margin so a tall unit forming one
  // endpoint (the fridge) never reports itself as an obstruction.
  const dx = end.x - start.x;
  const dz = end.z - start.z;
  let low = 0.08;
  let high = 0.92;
  const clip = (p: number, q: number): boolean => {
    if (p === 0) return q >= 0;
    const ratio = q / p;
    if (p < 0) low = Math.max(low, ratio);
    else high = Math.min(high, ratio);
    return low <= high;
  };
  return clip(-dx, start.x - rect.minX)
    && clip(dx, rect.maxX - start.x)
    && clip(-dz, start.z - rect.minZ)
    && clip(dz, rect.maxZ - start.z);
}

/**
 * Work-triangle travel begins at the usable front of an appliance, not at the
 * centre of its carcass. Measuring centre-to-centre made the route appear to
 * pass through a pantry beside a fridge and inflated large-room triangles by
 * roughly one cabinet depth at every leg.
 */
function workingAccessPoint(item: PlacedItem): { x: number; z: number } {
  const reach = item.depth / 2 + 100;
  const rotation = ((item.rotation % 360) + 360) % 360;
  if (rotation === 0) return { x: item.x, z: item.z + reach };
  if (rotation === 180) return { x: item.x, z: item.z - reach };
  if (rotation === 90) return { x: item.x - reach, z: item.z };
  if (rotation === 270) return { x: item.x + reach, z: item.z };
  return { x: item.x, z: item.z };
}

// ─── The registry ───────────────────────────────────────────────────────────
// Order is stable and deterministic (the sweep and de-dup rely on it).

export const RULES: Rule[] = [
  {
    id: 'out-of-room', tier: 'hard', scope: 'spatial',
    title: 'Cabinet inside the room',
    why: 'Every cabinet must physically fit within the room outline.',
    evaluate: ({ design, room }) => design.items.flatMap(item => {
      const r = itemRect(item);
      return (r.minX < -1 || r.maxX > room.width + 1 || r.minZ < -1 || r.maxZ > room.depth + 1)
        ? [finding('out-of-room', 'hard', `${item.definitionId} extends outside the room`, [item.instanceId])]
        : [];
    }),
  },
  {
    id: 'overlap', tier: 'hard', scope: 'spatial',
    title: 'No overlapping cabinets',
    why: 'Two cabinets cannot occupy the same floor space.',
    evaluate: ({ floorItems }) => {
      const out: RuleFinding[] = [];
      for (let i = 0; i < floorItems.length; i++) {
        for (let j = i + 1; j < floorItems.length; j++) {
          if (rectsOverlap(itemRect(floorItems[i]), itemRect(floorItems[j]))) {
            out.push(finding('overlap', 'hard',
              `${floorItems[i].definitionId} overlaps ${floorItems[j].definitionId}`,
              [floorItems[i].instanceId, floorItems[j].instanceId]));
          }
        }
      }
      return out;
    },
  },
  {
    id: 'allowed-wall', tier: 'hard', scope: 'relational',
    title: 'Customer-selected cabinet walls',
    why: 'A design must use exactly the walls the customer nominated for cabinetry.',
    evaluate: ({ design, brief }) => {
      const allowed = brief?.allowedWalls?.length ? new Set(brief.allowedWalls) : null;
      if (!allowed) return [];
      const used = new Set(design.runWalls);
      return [
        ...design.runWalls
          .filter(wall => !allowed.has(wall))
          .map(wall => finding(
            'allowed-wall',
            'hard',
            `The design places cabinets on wall ${wall}, which was not selected for cabinetry`,
          )),
        ...[...allowed]
          .filter(wall => !used.has(wall))
          .map(wall => finding(
            'selected-wall-missing',
            'hard',
            `The design leaves out wall ${wall}, which was selected for cabinetry`,
          )),
      ];
    },
  },
  {
    id: 'wall-run-range', tier: 'hard', scope: 'relational',
    title: 'Customer-selected partial wall runs',
    why: 'Cabinets must stay inside the start and finish points selected for each wall.',
    evaluate: ({ design, brief }) => {
      if (!brief?.wallRanges) return [];
      return Object.entries(brief.wallRanges).flatMap(([wallKey, requested]) => {
        if (!requested) return [];
        const wall = wallKey as Wall;
        const expected = rangeForWall(brief, wall);
        const actual = design.runRanges.find(range => range.wall === wall);
        if (!actual || (actual.startMm >= expected.startMm - 1 && actual.endMm <= expected.endMm + 1)) {
          return [];
        }
        return [finding(
          'wall-run-range',
          'hard',
          `The design extends beyond the selected ${expected.startMm}–${expected.endMm} mm range on wall ${wall}`,
        )];
      });
    },
  },
  {
    id: 'wall-end-filler', tier: 'hard', scope: 'relational',
    title: 'Ordinary cabinets are scribed to room walls',
    why: 'A standard cabinet or tall bank finishing against a wall needs a normal filler so doors, handles and installation tolerances clear the wall. A housed fridge uses the clearance and overhead filler within its reserved opening.',
    evaluate: ({ design, room }) => design.sourceSpec.runs.flatMap(run => {
      const range = design.runRanges.find(candidate => candidate.wall === run.wall);
      if (!range || run.segments.length === 0) return [];
      const connectsAt = (at: 'start' | 'end') => design.sourceSpec.runs.some(other =>
        other.wall !== run.wall
        && sharedCornerAt(run.wall, other.wall) === at
        && runTouchesSharedCorner(design, room, run.wall, other.wall));
      const physicalStart = run.fromEnd ? run.segments.at(-1) : run.segments[0];
      const physicalEnd = run.fromEnd ? run.segments[0] : run.segments.at(-1);
      const protectedEdge = (segment: Segment | undefined) => segment?.kind === 'filler'
        || (segment?.kind === 'cabinet' && (
          segment.role === 'corner'
          || (run.wallCabinets && segment.role === 'fridge-gap')
        ));
      const findings: RuleFinding[] = [];
      if (range.startMm <= 25 && !connectsAt('start') && !protectedEdge(physicalStart)) {
        findings.push(finding(
          'wall-end-filler',
          'hard',
          `The ${run.wall} run starts against a room wall without a normal filler`,
        ));
      }
      if (range.endMm >= wallLength(run.wall, room) - 25
        && !connectsAt('end') && !protectedEdge(physicalEnd)) {
        findings.push(finding(
          'wall-end-filler',
          'hard',
          `The ${run.wall} run ends against a room wall without a normal filler`,
        ));
      }
      return findings;
    }),
  },
  {
    id: 'duplicate-run-wall', tier: 'hard', scope: 'relational',
    title: 'One run definition per wall',
    why: 'A wall is solved as one openings-aware run; duplicate run definitions can overlap or bypass layout-shape checks.',
    evaluate: ({ design }) => {
      const seen = new Set<Wall>();
      const duplicates = new Set<Wall>();
      for (const wall of design.runWalls) {
        if (seen.has(wall)) duplicates.add(wall);
        seen.add(wall);
      }
      return [...duplicates].map(wall => finding(
        'duplicate-run-wall',
        'hard',
        `Wall ${wall} is defined more than once`,
      ));
    },
  },
  {
    id: 'faces-wall', tier: 'hard', scope: 'relational',
    title: 'Cabinets face the room',
    why: 'A cabinet against a wall must open into the room, not into the wall — the rotation must match the wall it sits on.',
    evaluate: ({ floorItems, room }) => floorItems.flatMap(item => {
      if (item.definitionId.includes('corner')) return [];
      const r = itemRect(item);
      const touching: Wall[] = [];
      if (r.minZ <= 30) touching.push('N');
      if (r.maxX >= room.width - 30) touching.push('E');
      if (r.maxZ >= room.depth - 30) touching.push('S');
      if (r.minX <= 30) touching.push('W');
      if (touching.length === 0) return [];
      const rot = ((Math.round(item.rotation) % 360) + 360) % 360;
      return touching.some(w => rot === WALL_ROTATION[w])
        ? []
        : [finding('faces-wall', 'hard',
            `${item.definitionId} touches wall(s) ${touching.join('/')} with rotation ${rot} — it faces a wall, not the room`,
            [item.instanceId])];
    }),
  },
  {
    id: 'doorway-tight', tier: 'safety', scope: 'spatial',
    title: 'Scribe gap at doorways',
    why: 'A cabinet built hard against a door or walkway architrave has no scribe/clearance — leave a filler.',
    evaluate: ({ floorItems, room }) => {
      const out: RuleFinding[] = [];
      for (const o of room.openings) {
        if (o.type !== 'door' && o.type !== 'walkway') continue;
        const span = { start: o.offsetMm, end: o.offsetMm + o.widthMm };
        for (const item of floorItems) {
          const r = itemRect(item);
          let t: { start: number; end: number } | null = null;
          let againstWall = false;
          if (o.wall === 'N') { againstWall = r.minZ <= 30; t = { start: r.minX, end: r.maxX }; }
          if (o.wall === 'S') { againstWall = r.maxZ >= room.depth - 30; t = { start: room.width - r.maxX, end: room.width - r.minX }; }
          if (o.wall === 'E') { againstWall = r.maxX >= room.width - 30; t = { start: r.minZ, end: r.maxZ }; }
          if (o.wall === 'W') { againstWall = r.minX <= 30; t = { start: room.depth - r.maxZ, end: room.depth - r.minZ }; }
          if (!againstWall || !t) continue;
          const gap = Math.max(span.start - t.end, t.start - span.end);
          if (gap > -1 && gap < 25 && !item.fillerLeft && !item.fillerRight) {
            out.push(finding('doorway-tight', 'safety',
              `${item.definitionId} is ${Math.max(0, Math.round(gap))}mm from the ${o.type} on wall ${o.wall} with no filler`,
              [item.instanceId]));
          }
        }
      }
      return out;
    },
  },
  {
    id: 'door-swing', tier: 'safety', scope: 'spatial',
    title: 'Door swing clearance',
    why: 'An in-swinging door needs floor space to open — a cabinet in its arc will foul it.',
    evaluate: ({ floorItems, room }) => {
      const out: RuleFinding[] = [];
      for (const o of room.openings) {
        if (o.type !== 'door' || o.swing === 'out' || o.swing === 'slider') continue;
        const c = wallPointWorld(o.wall, o.offsetMm + o.widthMm / 2, room);
        const half = o.widthMm / 2;
        const arc = { minX: c.x - half, maxX: c.x + half, minZ: c.z - half, maxZ: c.z + half };
        for (const item of floorItems) {
          if (rectsOverlap(itemRect(item), arc)) {
            out.push(finding('door-swing', 'safety', `${item.definitionId} may block the door swing on wall ${o.wall}`, [item.instanceId]));
          }
        }
      }
      return out;
    },
  },
  {
    id: 'narrow-aisle', tier: 'hard', scope: 'spatial',
    title: 'Island aisle width',
    why: `An aisle beside an island narrower than ${MIN_AISLE}mm is not usable.`,
    evaluate: ({ floorItems, islandItems }) => {
      const out: RuleFinding[] = [];
      const workingFootprint = (item: PlacedItem) => item.height <= 1000
        ? benchtopRect(item)
        : itemRect(item);
      for (const isl of islandItems) {
        for (const other of floorItems) {
          if (islandItems.includes(other)) continue;
          const a = workingFootprint(isl), b = workingFootprint(other);
          const overlapsX = a.minX < b.maxX && a.maxX > b.minX;
          const overlapsZ = a.minZ < b.maxZ && a.maxZ > b.minZ;
          const gap = overlapsX
            ? Math.max(b.minZ - a.maxZ, a.minZ - b.maxZ)
            : overlapsZ
              ? Math.max(b.minX - a.maxX, a.minX - b.maxX)
              : Number.POSITIVE_INFINITY;
          if (gap > 0 && gap < MIN_AISLE) {
            out.push(finding('narrow-aisle', 'hard',
              `Clear benchtop-to-benchtop aisle is ${Math.round(gap)}mm (min ${MIN_AISLE}mm)`,
              [isl.instanceId, other.instanceId]));
          }
        }
      }
      return out;
    },
  },
  {
    id: 'narrow-galley', tier: 'hard', scope: 'spatial',
    title: 'Galley aisle width',
    why: `Two facing runs need at least ${MIN_FACING_AISLE}mm between them to work in.`,
    evaluate: ({ floorItems, islandItems }) => {
      const nRun = floorItems.filter(i => i.rotation === 0);
      const sRun = floorItems.filter(i => i.rotation === 180 && !islandItems.includes(i));
      if (!nRun.length || !sRun.length) return [];
      const gap = Math.min(...sRun.map(i => itemRect(i).minZ)) - Math.max(...nRun.map(i => itemRect(i).maxZ));
      return gap < MIN_FACING_AISLE
        ? [finding('narrow-galley', 'hard', `Galley aisle ${Math.round(gap)}mm (min ${MIN_FACING_AISLE}mm)`)]
        : [];
    },
  },
  {
    id: 'no-sink', tier: 'hard', scope: 'relational',
    title: 'Has a sink',
    why: 'A kitchen must have a sink.',
    evaluate: ({ design }) => design.rolePositions.sink ? [] : [finding('no-sink', 'hard', 'Design has no sink cabinet')],
  },
  {
    id: 'no-cooktop', tier: 'hard', scope: 'relational',
    title: 'Has a cooktop',
    why: 'A kitchen must have a cooktop.',
    evaluate: ({ design }) => design.rolePositions.cooktop ? [] : [finding('no-cooktop', 'hard', 'Design has no cooktop cabinet')],
  },
  {
    id: 'cooktop-window', tier: 'safety', scope: 'relational',
    title: 'Cooktop stays clear of windows',
    why: 'A cooktop in front of a window conflicts with safe extraction, window operation and the normal rangehood position. It is only retained when a compact room has no safer layout.',
    evaluate: ({ design, room }) => {
      const cooktop = design.rolePositions.cooktop;
      if (!cooktop || cooktop.wall === 'island') return [];
      const cooktopEnd = cooktop.startMm + cooktop.widthMm;
      const overlappingWindow = room.openings.find(opening =>
        opening.type === 'window'
        && opening.wall === cooktop.wall
        && opening.offsetMm < cooktopEnd - 1
        && opening.offsetMm + opening.widthMm > cooktop.startMm + 1);
      return overlappingWindow
        ? [finding(
            'cooktop-window',
            'safety',
            `Cooktop overlaps the window on wall ${cooktop.wall}; use this only when the room has no safe alternative`,
            [cooktop.item.instanceId],
          )]
        : [];
    },
  },
  {
    id: 'sink-side-clearance', tier: 'safety', scope: 'relational',
    title: 'Sink stays clear of exposed ends and tall panels',
    why: `A sink needs at least ${SINK_SIDE_CLEARANCE_MIN}mm of adjoining low bench or a usable corner on both sides. This keeps the bowl away from an exposed run end, wall or tall panel unless a compact kitchen leaves no alternative.`,
    evaluate: ({ design }) => design.sourceSpec.runs.flatMap(run => {
      const index = run.segments.findIndex(segment =>
        segment.kind === 'cabinet' && segment.role === 'sink');
      if (index < 0) return [];
      const left = contiguousSinkSideFrom(run.segments, index - 1, -1);
      const right = contiguousSinkSideFrom(run.segments, index + 1, 1);
      return left < SINK_SIDE_CLEARANCE_MIN || right < SINK_SIDE_CLEARANCE_MIN
        ? [finding(
            'sink-side-clearance',
            'safety',
            `Sink side bench is ${left}mm / ${right}mm (preferred minimum ${SINK_SIDE_CLEARANCE_MIN}mm on each side)`,
            design.rolePositions.sink ? [design.rolePositions.sink.item.instanceId] : undefined,
          )]
        : [];
    }),
  },
  {
    id: 'no-fridge', tier: 'hard', scope: 'relational',
    title: 'Has a fridge space',
    why: 'A kitchen must have somewhere for the fridge.',
    evaluate: ({ design }) => design.rolePositions['fridge-gap'] ? [] : [finding('no-fridge', 'hard', 'Design has no fridge space')],
  },
  {
    id: 'no-dishwasher', tier: 'hard', scope: 'relational',
    title: 'Dishwasher placed when requested',
    why: 'If the customer asked for a dishwasher, the design must include its opening.',
    evaluate: ({ design, brief }) =>
      brief?.appliances.dishwasher && !design.rolePositions.dishwasher
        ? [finding('no-dishwasher', 'hard', 'Dishwasher requested but not placed')]
        : [],
  },
  {
    id: 'dishwasher-not-adjacent', tier: 'hard', scope: 'relational',
    title: 'Dishwasher beside the sink',
    why: 'The dishwasher shares the sink’s plumbing, so it must sit immediately next to the sink cabinet.',
    evaluate: ({ design, brief }) => {
      const sink = design.rolePositions.sink;
      const dishwasher = design.rolePositions.dishwasher;
      if (!brief?.appliances.dishwasher || !sink || !dishwasher) return [];
      const adjacent = sink.wall === dishwasher.wall && (
        Math.abs((sink.startMm + sink.widthMm) - dishwasher.startMm) <= 1
        || Math.abs((dishwasher.startMm + dishwasher.widthMm) - sink.startMm) <= 1
      );
      return adjacent ? [] : [finding('dishwasher-not-adjacent', 'hard',
        'Dishwasher must be immediately beside the sink cabinet',
        [sink.item.instanceId, dishwasher.item.instanceId])];
    },
  },
  {
    id: 'tall-unit-run-end', tier: 'hard', scope: 'relational',
    title: 'Tall units stay at run ends',
    why: 'A pantry, fridge or oven tower in the middle of a bench breaks preparation flow and visually splits the kitchen.',
    evaluate: ({ design }) => design.sourceSpec.runs.flatMap(run => {
      const cabinetSegments = run.segments.filter(segment => segment.kind === 'cabinet');
      const tallIndexes = cabinetSegments
        .map((segment, index) => TALL_ROLES.has(segment.role) ? index : -1)
        .filter(index => index >= 0);
      if (tallIndexes.length === 0) return [];
      const baseIndexes = cabinetSegments
        .map((segment, index) => !TALL_ROLES.has(segment.role) ? index : -1)
        .filter(index => index >= 0);
      const firstBase = Math.min(...baseIndexes);
      const lastBase = Math.max(...baseIndexes);
      const midRun = tallIndexes.some(index => {
        const segment = cabinetSegments[index];
        const protectedByLeadingBuffer = ['corner', 'corner-buffer'].includes(cabinetSegments[0]?.role)
          && cabinetSegments.slice(1, index + 1).every(isTallSegment);
        const protectedByTrailingBuffer = ['corner', 'corner-buffer'].includes(cabinetSegments.at(-1)?.role)
          && cabinetSegments.slice(index, -1).every(isTallSegment);
        const cornerProtectedOven = index === 1
          && segment.role === 'oven-tower'
          && cabinetSegments[0]?.role === 'doors'
          && segmentWidth(cabinetSegments[0]) <= OVEN_TOWER_CORNER_CLEARANCE;
        return index > firstBase && index < lastBase
          && !protectedByLeadingBuffer && !protectedByTrailingBuffer && !cornerProtectedOven;
      });
      return midRun
        ? [finding('tall-unit-run-end', 'hard', `A tall unit interrupts the working bench on wall ${run.wall}`)]
        : [];
    }),
  },
  {
    id: 'tall-unit-cluster', tier: 'hard', scope: 'relational',
    title: 'Tall units form one continuous bank',
    why: 'Fridge, oven tower and pantry belong together at a run end; scattering them across working walls breaks bench flow and visual order.',
    evaluate: ({ design }) => {
      const tallRuns = design.sourceSpec.runs
        .map(run => ({
          run,
          cabinets: run.segments.filter(segment => segment.kind === 'cabinet'),
        }))
        .map(entry => ({
          ...entry,
          tallIndexes: entry.cabinets
            .map((segment, index) => isTallSegment(segment) ? index : -1)
            .filter(index => index >= 0),
        }))
        .filter(entry => entry.tallIndexes.length > 0);
      const tallCount = tallRuns.reduce((sum, entry) => sum + entry.tallIndexes.length, 0);
      if (tallCount <= 1) return [];
      if (tallRuns.length > 1) {
        return [finding(
          'tall-unit-cluster',
          'hard',
          'Fridge, oven tower and pantry are split across different walls instead of one tall-unit bank',
        )];
      }
      const indexes = tallRuns[0].tallIndexes;
      const contiguous = indexes.at(-1)! - indexes[0] + 1 === indexes.length;
      return contiguous
        ? []
        : [finding(
            'tall-unit-cluster',
            'hard',
            `Tall units are separated by a base cabinet on wall ${tallRuns[0].run.wall}`,
          )];
    },
  },
  {
    id: 'tall-unit-workflow-break', tier: 'hard', scope: 'relational',
    title: 'Sink-to-cooktop bench remains unbroken',
    why: 'Tall cabinetry must never split the main sink-to-cooktop preparation run.',
    evaluate: ({ design }) => design.sourceSpec.runs.flatMap(run => {
      const sink = run.segments.findIndex(segment => segment.kind === 'cabinet' && segment.role === 'sink');
      const cooktop = run.segments.findIndex(segment => segment.kind === 'cabinet' && segment.role === 'cooktop');
      if (sink < 0 || cooktop < 0) return [];
      const low = Math.min(sink, cooktop);
      const high = Math.max(sink, cooktop);
      return run.segments.slice(low + 1, high).some(isTallSegment)
        ? [finding('tall-unit-workflow-break', 'hard', `A tall unit breaks the sink-to-cooktop bench on wall ${run.wall}`)]
        : [];
    }),
  },
  {
    id: 'fridge-room-corner-clearance', tier: 'hard', scope: 'spatial',
    title: 'Fridge doors clear perpendicular room walls',
    why: `A fridge needs at least ${FRIDGE_ROOM_CORNER_CLEARANCE_MM}mm between it and a physical room corner so its doors and internal drawers can open fully.`,
    evaluate: ({ design, room }) => {
      const fridge = design.rolePositions['fridge-gap'];
      if (!fridge || fridge.wall === 'island') return [];
      const length = wallLength(fridge.wall, room);
      const startClearance = fridge.startMm;
      const endClearance = length - fridge.startMm - fridge.widthMm;
      const sourceRun = fridge.item.layoutRunIndex === undefined
        ? undefined
        : design.sourceSpec.runs[fridge.item.layoutRunIndex];
      const housed = sourceRun?.wallCabinets === true;
      // A housed opening may deliberately meet the wall: its nominal width
      // already includes the appliance's side allowance and the overhead is
      // closed with a normal filler. A small accidental sliver is still invalid.
      const startIsValid = startClearance >= FRIDGE_ROOM_CORNER_CLEARANCE_MM
        || (housed && startClearance <= FRIDGE_SIDE_CLEARANCE_MM + 1);
      const endIsValid = endClearance >= FRIDGE_ROOM_CORNER_CLEARANCE_MM
        || (housed && endClearance <= FRIDGE_SIDE_CLEARANCE_MM + 1);
      if (startIsValid && endIsValid) return [];
      return [finding(
        'fridge-room-corner-clearance',
        'hard',
        `Fridge door clearance is ${Math.max(0, Math.round(startClearance))}mm / ${Math.max(0, Math.round(endClearance))}mm from the room corners (minimum ${FRIDGE_ROOM_CORNER_CLEARANCE_MM}mm)`,
        [fridge.item.instanceId],
      )];
    },
  },
  {
    id: 'corner-resolution', tier: 'hard', scope: 'relational',
    title: 'Every internal corner is deliberately resolved',
    why: 'Usable corner hardware or an explicit no-fit void prevents valuable space being lost behind filler panels.',
    evaluate: ({ design, room }) => {
      const findings: RuleFinding[] = [];
      for (let a = 0; a < design.sourceSpec.runs.length; a++) {
        for (let b = a + 1; b < design.sourceSpec.runs.length; b++) {
          const first = design.sourceSpec.runs[a];
          const second = design.sourceSpec.runs[b];
          if (!runTouchesSharedCorner(design, room, first.wall, second.wall)) continue;
          const pair = [...first.segments, ...second.segments];
          const resolved = pair.some(segment => segment.kind === 'cabinet' && segment.role === 'corner')
            || pair.some(segment => segment.kind === 'gap'
              && /corner/i.test(segment.reason) && /(void|no.?fit|walk.?in)/i.test(segment.reason));
          if (!resolved) {
            findings.push(finding(
              'corner-resolution',
              'hard',
              `The internal corner between walls ${first.wall} and ${second.wall} has no mapped corner unit or explicit no-fit reason`,
            ));
          }
        }
      }
      return findings;
    },
  },
  {
    id: 'style-composition-fidelity', tier: 'hard', scope: 'relational',
    title: 'Style family changes composition',
    why: 'A style is a cabinet-composition system, not a material wrap applied to the same kitchen.',
    evaluate: ({ design }) => {
      const profile = styleProfile(design.sourceSpec.style.familyId);
      if (!profile) return [];
      const plans = design.sourceSpec.runs.map(run => run.upperPlan).filter(Boolean);
      const maxCoverage = Math.max(0, ...plans.map(plan => plan?.coverageRatio ?? 0));
      const maxShelving = Math.max(0, ...plans.map(plan => plan?.openShelfRatio ?? 0));
      const features = new Set(design.sourceSpec.style.compositionFeatureIds ?? []);
      const findings: RuleFinding[] = [];
      for (const required of profile.requiredFeatureElements) {
        if (!features.has(required)) findings.push(finding('style-required-feature', 'hard', `${profile.name} requires ${required}`));
      }
      if (profile.id === 'hamptons' && maxCoverage < .78) {
        findings.push(finding('style-overhead-density', 'hard', 'Hamptons requires a generous overhead run'));
      }
      if (profile.id === 'scandinavian' && maxCoverage > .55) {
        findings.push(finding('style-overhead-density', 'hard', 'Scandinavian must not use a full overhead run'));
      }
      if (profile.id === 'coastal' && maxShelving < .45) {
        findings.push(finding('style-open-shelving', 'hard', 'Coastal requires visible open shelving'));
      }
      return findings;
    },
  },
  {
    id: 'corner-integrity', tier: 'hard', scope: 'relational',
    title: 'Corner cabinets resolve correctly',
    why: 'A corner position must use a real square pie-cut cabinet with linked bi-fold doors, or a correctly oriented blind-corner fallback.',
    evaluate: ({ floorItems }) => floorItems.flatMap(item => {
      if (!item.definitionId.includes('corner')) return [];
      if (item.definitionId.includes('pie_cut')) {
        const findings: RuleFinding[] = [];
        if (Math.abs(item.width - item.depth) > 1) {
          findings.push(finding(
            'corner-integrity',
            'hard',
            `${item.definitionId} must use a square footprint so both arms meet the adjoining runs`,
            [item.instanceId],
          ));
        }
        if (Math.abs(item.width - 900) > 1) {
          findings.push(finding(
            'corner-integrity',
            'hard',
            `${item.definitionId} must use the mapped 900mm bi-fold corner size`,
            [item.instanceId],
          ));
        }
        return findings;
      }
      if (!item.definitionId.includes('blind')) return [];
      if (!item.blindSide) {
        return [finding(
          'corner-integrity',
          'hard',
          `${item.definitionId} is a corner cabinet with no blind side set`,
          [item.instanceId],
        )];
      }
      const front = blindCornerFrontLayout(item.width, item.depth, item.blindSide);
      const findings: RuleFinding[] = [];
      if (Math.abs(item.depth - (575 + BLIND_CORNER_RETURN_MM)) > 1) {
        findings.push(finding(
          'corner-integrity',
          'hard',
          `${item.definitionId} does not include its ${BLIND_CORNER_RETURN_MM}mm built-in return`,
          [item.instanceId],
        ));
      }
      if (front.accessWidthMm < BLIND_CORNER_MIN_ACCESS_MM) {
        findings.push(finding(
            'corner-integrity',
            'hard',
            `${item.definitionId} leaves only ${Math.round(front.accessWidthMm)}mm of usable door opening (minimum ${BLIND_CORNER_MIN_ACCESS_MM}mm)`,
            [item.instanceId],
          ));
      }
      return findings;
    }),
  },
  {
    id: 'blind-corner-join', tier: 'hard', scope: 'spatial',
    title: 'Blind-corner return and adjoining run form one joint',
    why: 'The first base cabinet on the adjoining run must finish directly into the blind unit return, and their benchtops must close the corner with no gap.',
    evaluate: ({ floorItems }) => floorItems.flatMap(corner => {
      if (!corner.definitionId.includes('corner') || !corner.blindSide) return [];
      const cornerRotation = ((corner.rotation % 360) + 360) % 360;
      const cornerCarcase = itemRect(corner);
      const adjacent = floorItems.find(candidate => {
        if (candidate === corner || candidate.height > 1000
          || candidate.definitionId.includes('corner')) return false;
        const candidateRotation = ((candidate.rotation % 360) + 360) % 360;
        const perpendicular = Math.abs(cornerRotation - candidateRotation) % 180 === 90;
        return perpendicular && rectsJoin(cornerCarcase, itemRect(candidate));
      });
      if (!adjacent) {
        return [finding(
          'blind-corner-join',
          'hard',
          `${corner.definitionId} has no adjoining base cabinet linked to its built-in return`,
          [corner.instanceId],
        )];
      }
      if (!rectsJoin(benchtopRect(corner), benchtopRect(adjacent))) {
        return [finding(
          'blind-corner-join',
          'hard',
          `The benchtop above ${adjacent.definitionId} does not join the blind-corner benchtop`,
          [corner.instanceId, adjacent.instanceId],
        )];
      }
      return [];
    }),
  },
  {
    id: 'cooking-appliance-corner-clearance', tier: 'hard', scope: 'spatial',
    title: 'Cooking appliances clear inside corners',
    why: 'Cooktops follow the nominated appliance side-clearance instructions; before a product is confirmed the planner uses 200mm for gas and 150mm for induction. Oven towers retain a larger working clearance for doors and handles.',
    evaluate: ({ design, room, brief }) => {
      const cookingRoles = [
        ['cooktop', design.rolePositions.cooktop],
        ['oven-tower', design.rolePositions['oven-tower']],
      ] as const;
      const rangeFor = (wall: Wall) => design.runRanges.find(range => range.wall === wall);
      const touches = (wall: Wall, end: 'start' | 'end') => {
        const range = rangeFor(wall);
        if (!range) return false;
        return end === 'start'
          ? range.startMm <= 25
          : range.endMm >= wallLength(wall, room) - 25;
      };

      return cookingRoles.flatMap(([role, position]) => {
        if (!position || position.wall === 'island') return [];
        const length = wallLength(position.wall, room);
        const requiredClearance = role === 'oven-tower'
          ? OVEN_TOWER_CORNER_CLEARANCE
          : brief?.appliances.cooktop === 'gas'
            ? GAS_COOKTOP_COMBUSTIBLE_SIDE_CLEARANCE
            : INDUCTION_COOKTOP_SIDE_CLEARANCE_FALLBACK;
        const clearanceBasis = role === 'oven-tower'
          ? 'oven-door working clearance'
          : brief?.appliances.cooktop === 'gas'
            ? 'gas fallback beside an unprotected combustible side'
            : 'induction fallback until the appliance instructions are confirmed';
        if (role === 'cooktop' && design.runWalls.length > 1) {
          const physicalClearance = Math.min(
            position.startMm,
            length - position.startMm - position.widthMm,
          );
          if (physicalClearance < requiredClearance) {
            const isUnderbenchOven = brief?.appliances.oven !== undefined
              && !design.rolePositions['oven-tower'];
            return [finding(
              'cooking-appliance-corner-clearance',
              'hard',
              `${isUnderbenchOven ? 'Under-bench oven and cooktop' : 'Cooktop'} is only ${Math.max(0, Math.round(physicalClearance))}mm from a room corner (planner minimum ${requiredClearance}mm: ${clearanceBasis}; confirm the selected appliance instructions)`,
              [position.item.instanceId],
            )];
          }
        }
        for (const adjacentWall of design.runWalls) {
          if (adjacentWall === position.wall) continue;
          const applianceCorner = sharedCornerAt(position.wall, adjacentWall);
          const adjacentCorner = sharedCornerAt(adjacentWall, position.wall);
          if (!applianceCorner || !adjacentCorner
            || !touches(position.wall, applianceCorner)
            || !touches(adjacentWall, adjacentCorner)) {
            continue;
          }
          const clearance = applianceCorner === 'start'
            ? position.startMm
            : length - position.startMm - position.widthMm;
          if (clearance >= requiredClearance) continue;

          const isUnderbenchOven = role === 'cooktop'
            && brief?.appliances.oven !== undefined
            && !design.rolePositions['oven-tower'];
          const label = role === 'oven-tower'
            ? 'Oven tower'
            : isUnderbenchOven ? 'Under-bench oven and cooktop' : 'Cooktop';
          return [finding(
            'cooking-appliance-corner-clearance',
            'hard',
            `${label} is only ${Math.max(0, Math.round(clearance))}mm from an inside corner (planner minimum ${requiredClearance}mm: ${clearanceBasis}; confirm the selected appliance instructions)`,
            [position.item.instanceId],
          )];
        }
        return [];
      });
    },
  },
  {
    id: 'appliance-gap-fit', tier: 'safety', scope: 'relational',
    title: 'Appliance openings fit the appliance',
    why: 'The sink cabinet, fridge space and dishwasher opening must be wide enough for the actual appliance.',
    evaluate: ({ design, brief }) => {
      const out: RuleFinding[] = [];
      const sink = design.rolePositions.sink;
      const requiredSinkCabinet = brief?.appliances.sinkCabinetWidthMm;
      if (sink && requiredSinkCabinet && sink.widthMm + 1 < requiredSinkCabinet) {
        out.push(finding('appliance-gap-fit', 'safety',
          `Sink cabinet is ${Math.round(sink.widthMm)}mm but the selected sink needs ${requiredSinkCabinet}mm`,
          [sink.item.instanceId]));
      }
      const fridge = design.rolePositions['fridge-gap'];
      const nominated = brief?.appliances.fridgeWidthMm ?? 900;
      const requiredOpening = brief?.appliances.fridgeOpeningWidthMm
        ?? fridgeOpeningWidthMm(nominated);
      if (fridge && fridge.widthMm + 20 < requiredOpening) {
        out.push(finding('appliance-gap-fit', 'safety',
          `Fridge space is ${fridge.widthMm}mm but a ${nominated}mm fridge needs ${requiredOpening}mm including 50mm clearance on each side`,
          [fridge.item.instanceId]));
      }
      const dw = design.rolePositions.dishwasher;
      if (dw && dw.widthMm < 600) {
        out.push(finding('appliance-gap-fit', 'safety',
          `Dishwasher opening is ${dw.widthMm}mm (a standard dishwasher needs 600mm)`,
          [dw.item.instanceId]));
      }
      return out;
    },
  },
  {
    id: 'oven-housing-fit', tier: 'hard', scope: 'relational',
    title: 'Oven housing matches the selected oven',
    why: 'A nominated oven must never be presented inside a narrower cabinet.',
    evaluate: ({ design, brief }) => {
      if (!brief?.appliances.oven) return [];
      const requiredWidthMm = Number(brief.appliances.oven);
      const host = design.rolePositions['oven-tower'] ?? design.rolePositions.cooktop;
      if (!host || host.widthMm + 1 >= requiredWidthMm) return [];
      return [finding(
        'oven-housing-fit',
        'hard',
        `${requiredWidthMm}mm oven is assigned to a ${Math.round(host.widthMm)}mm cabinet`,
        [host.item.instanceId],
      )];
    },
  },
  {
    id: 'replumb', tier: 'safety', scope: 'spatial',
    title: 'Sink near existing plumbing',
    why: 'A sink far from the existing drain means re-plumbing — extra cost the customer should know about.',
    evaluate: ({ design, room }) => {
      const sink = design.rolePositions.sink;
      const drain = room.services.find(s => s.type === 'drain') ?? room.services.find(s => s.type === 'water-supply');
      if (!sink || !drain) return [];
      const d = dist({ x: sink.item.x, z: sink.item.z }, servicePointWorld(drain, room));
      return d > SINK_DRAIN_MAX
        ? [finding('replumb', 'safety', `Sink is ${(d / 1000).toFixed(1)}m from existing plumbing — re-plumbing will be required`)]
        : [];
    },
  },
  {
    id: 'gas-move', tier: 'safety', scope: 'spatial',
    title: 'Gas cooktop near the gas point',
    why: 'A gas cooktop far from the gas point means gas work — extra cost to flag.',
    evaluate: ({ design, room, brief }) => {
      const cooktop = design.rolePositions.cooktop;
      const gas = room.services.find(s => s.type === 'gas');
      if (!cooktop || brief?.appliances.cooktop !== 'gas' || !gas) return [];
      const d = dist({ x: cooktop.item.x, z: cooktop.item.z }, servicePointWorld(gas, room));
      return d > GAS_MAX
        ? [finding('gas-move', 'safety', `Gas cooktop is ${(d / 1000).toFixed(1)}m from the gas point — gas work required`)]
        : [];
    },
  },
  {
    id: 'cooktop-landing', tier: 'safety', scope: 'relational',
    title: 'Cooktop landing zones',
    why: 'A cooktop needs measured bench space on both sides to set down hot pans safely.',
    evaluate: ({ design }) => design.sourceSpec.runs.flatMap(run => {
      const index = run.segments.findIndex(segment => segment.kind === 'cabinet' && segment.role === 'cooktop');
      if (index < 0) return [];
      const left = contiguousBenchFrom(run.segments, index - 1, -1);
      const right = contiguousBenchFrom(run.segments, index + 1, 1);
      return left < COOKTOP_LANDING_MIN || right < COOKTOP_LANDING_MIN
        ? [finding(
            'cooktop-landing',
            'safety',
            `Cooktop landing is ${left}mm / ${right}mm (minimum ${COOKTOP_LANDING_MIN}mm on each side)`,
            design.rolePositions.cooktop ? [design.rolePositions.cooktop.item.instanceId] : undefined,
          )]
        : [];
    }),
  },
  {
    id: 'fridge-landing', tier: 'safety', scope: 'relational',
    title: 'Fridge landing zone',
    why: 'A fridge needs an adjacent bench where groceries and containers can be set down safely.',
    evaluate: ({ design }) => design.sourceSpec.runs.flatMap(run => {
      const index = run.segments.findIndex(segment => segment.kind === 'cabinet' && segment.role === 'fridge-gap');
      if (index < 0) return [];
      const left = contiguousBenchFrom(run.segments, index - 1, -1);
      const right = contiguousBenchFrom(run.segments, index + 1, 1);
      const landing = Math.max(left, right);
      return landing < FRIDGE_LANDING_MIN
        ? [finding(
            'fridge-landing',
            'safety',
            `Fridge landing is ${landing}mm (minimum ${FRIDGE_LANDING_MIN}mm adjacent bench)`,
            design.rolePositions['fridge-gap'] ? [design.rolePositions['fridge-gap'].item.instanceId] : undefined,
          )]
        : [];
    }),
  },
  {
    id: 'island-exposed', tier: 'safety', scope: 'relational',
    title: 'Island ends finished',
    why: 'An island is seen from all sides, so its exposed ends need finished panels, not bare carcase.',
    evaluate: ({ islandItems }) => {
      if (islandItems.length === 0) return [];
      const hasLeft = islandItems.some(i => i.endPanelLeft);
      const hasRight = islandItems.some(i => i.endPanelRight);
      return (!hasLeft || !hasRight)
        ? [finding('island-exposed', 'safety', 'Island has an exposed carcase end with no finished panel')]
        : [];
    },
  },
  {
    id: 'triangle-size', tier: 'safety', scope: 'spatial',
    title: 'Work-triangle perimeter',
    why: 'The sink–cooktop–fridge triangle works best between 3.6m and 8m total.',
    evaluate: ({ design }) => {
      const { sink, cooktop } = design.rolePositions;
      const fridge = design.rolePositions['fridge-gap'];
      if (!sink || !cooktop || !fridge) return [];
      if (sink.wall === cooktop.wall && cooktop.wall === fridge.wall) return [];
      const pts = [sink.item, cooktop.item, fridge.item].map(workingAccessPoint);
      const perimeter = dist(pts[0], pts[1]) + dist(pts[1], pts[2]) + dist(pts[2], pts[0]);
      return (perimeter < TRIANGLE_MIN || perimeter > TRIANGLE_MAX)
        ? [finding('triangle-size', 'safety', `Work triangle ${(perimeter / 1000).toFixed(1)}m (required 3.6–8m)`)]
        : [];
    },
  },
  {
    id: 'triangle-leg', tier: 'safety', scope: 'spatial',
    title: 'Work-triangle legs',
    why: 'Each leg of the work triangle should be neither cramped nor a long walk.',
    evaluate: ({ design }) => {
      const { sink, cooktop } = design.rolePositions;
      const fridge = design.rolePositions['fridge-gap'];
      if (!sink || !cooktop || !fridge) return [];
      if (sink.wall === cooktop.wall && cooktop.wall === fridge.wall) return [];
      const pts = [sink.item, cooktop.item, fridge.item].map(workingAccessPoint);
      const legs = [dist(pts[0], pts[1]), dist(pts[1], pts[2]), dist(pts[2], pts[0])];
      for (const leg of legs) {
        if (leg < LEG_MIN) return [finding('triangle-leg', 'safety', `A work-triangle leg is under ${LEG_MIN}mm`)];
        if (leg > LEG_MAX) return [finding('triangle-leg', 'safety', `A work-triangle leg exceeds ${LEG_MAX}mm`)];
      }
      return [];
    },
  },
  {
    id: 'triangle-obstruction', tier: 'safety', scope: 'spatial',
    title: 'Work-triangle paths stay clear',
    why: 'A tall cabinet cannot stand in the walking path between the sink, cooktop and fridge.',
    evaluate: ({ design, floorItems }) => {
      const sink = design.rolePositions.sink?.item;
      const cooktop = design.rolePositions.cooktop?.item;
      const fridge = design.rolePositions['fridge-gap']?.item;
      if (!sink || !cooktop || !fridge) return [];
      const tall = floorItems.filter(item => item.height > 1500
        && item !== fridge
        // These 18mm panels are the fridge enclosure itself, not a separate
        // tall cabinet standing in a work-triangle path.
        && item.layoutRole !== 'fridge-side-panel');
      const legs = [
        [workingAccessPoint(sink), workingAccessPoint(cooktop)],
        [workingAccessPoint(cooktop), workingAccessPoint(fridge)],
        [workingAccessPoint(fridge), workingAccessPoint(sink)],
      ] as const;
      for (const blocker of tall) {
        if (legs.some(([start, end]) => segmentCrossesRect(start, end, itemRect(blocker)))) {
          return [finding(
            'triangle-obstruction',
            'safety',
            `${blocker.definitionId} blocks a work-triangle path`,
            [blocker.instanceId],
          )];
        }
      }
      return [];
    },
  },
  {
    id: 'prep-space', tier: 'safety', scope: 'relational',
    title: 'Continuous prep bench',
    why: 'A usable kitchen wants at least 900mm of uninterrupted bench to prepare food.',
    evaluate: ({ design, floorItems }) => {
      const { sink, cooktop } = design.rolePositions;
      const prepRun = floorItems.filter(i => i.height <= 800 && i.itemType === 'Cabinet'
        && !(sink && i === sink.item) && !(cooktop && i === cooktop.item));
      const hasPrep = prepRun.some(i => i.width >= 900)
        || prepRun.some(a => prepRun.some(b => a !== b && a.rotation === b.rotation
          && Math.abs(a.z - b.z) < 10 && Math.abs(Math.abs(a.x - b.x) - (a.width + b.width) / 2) < 20
          && a.width + b.width >= 900));
      return !hasPrep
        ? [finding('prep-space', 'safety', `Less than ${PREP_BENCH_MIN}mm of continuous prep bench`)]
        : [];
    },
  },
];

/** Reserved rule ids that need catalogue data (SKU/sink-bowl/appliance dims) or
 *  the resolved-segment stream, to be implemented in later phases. Documented
 *  here so the gap is visible rather than silent. */
export const RESERVED_RULE_IDS = ['sink-bowl-fit', 'run-end-panel', 'filler-complete', 'cutout-intersection'] as const;

/** Build the shared context once, then run every rule. Deterministic order. */
export function evaluateRules(design: CompiledDesign, room: RoomSpec, brief?: DesignBrief): RuleFinding[] {
  const floorItems = design.items.filter(i => i.y === 0);
  const islandItems = floorItems.filter(i => i.layoutRole === 'island');
  const ctx: RuleContext = { design, room, brief, floorItems, islandItems };
  return RULES.flatMap(rule => rule.evaluate(ctx));
}

/** Sweep/coverage view — every rule's id, tier and scope. The placement sweep
 *  can print this so rule coverage is visible (the 20-July defects hid because
 *  no rule existed for them; silent gaps must be countable). */
export const RULE_INDEX: { id: string; tier: RuleTier; scope: RuleScope; title: string }[] =
  RULES.map(({ id, tier, scope, title }) => ({ id, tier, scope, title }));

/** Plain-language "why" for a rule id — used by the design-explanation feature. */
export function ruleWhy(ruleId: string): string | undefined {
  return RULES.find(r => r.id === ruleId)?.why;
}
